# ui/ai_analysis_panel.py — v3
#
# CHANGES:
#   Added two new tabs:
#     ⚖️  Risk of Bias — RoB 2 (RCTs) / NOS (observational) per-article assessment
#     📋  GRADE / SoF   — GRADE certainty across all included studies + SoF table
#   Original four tabs unchanged.
#
# Architecture:
#   - study_classifier determines which RoB tool to apply per article
#   - rob2_assessor / nos_assessor run LLM signalling questions + deterministic algorithm
#   - grade_assessor aggregates across all studies for the overall evidence certainty
#   - All results cached in session_state (same pattern as existing tabs)






# ui/ai_analysis_panel.py — v3
#
# CHANGES:
#   Added two new tabs:
#     ⚖️  Risk of Bias — RoB 2 (RCTs) / NOS (observational) per-article assessment
#     📋  GRADE / SoF   — GRADE certainty across all included studies + SoF table
#   Original four tabs unchanged.
#
# Architecture:
#   - study_classifier determines which RoB tool to apply per article
#   - rob2_assessor / nos_assessor run LLM signalling questions + deterministic algorithm
#   - grade_assessor aggregates across all studies for the overall evidence certainty
#   - All results cached in session_state (same pattern as existing tabs)

import json
import logging
from typing import Dict, List, Optional

import pandas as pd
import streamlit as st

from pipeline.data_pooler        import extract_study_data, build_composite_table, StudyData
from pipeline.study_classifier   import classify_study, StudyDesign
from pipeline.rob2_assessor      import assess_rob2, RISK_EMOJI, RISK_LABEL
from pipeline.nos_assessor       import assess_nos
from pipeline.grade_assessor     import assess_grade, CERTAINTY_DISPLAY, CERTAINTY_EMOJI
from storage.repository import (
    ArticleRepository, ScreeningRepository, AdjudicationRepository
)
from storage.repository import ArticleRepository as _AR  # for stage2 counts

logger = logging.getLogger(__name__)

article_repo      = ArticleRepository()
screening_repo    = ScreeningRepository()
adjudication_repo = AdjudicationRepository()

SYSTEM_REVIEWER_IDS = {"final_resolved", "editor", "adjudicator"}


# ── AI Disclaimer ──────────────────────────────────────────────────────────────

def _render_ai_disclaimer() -> None:
    st.markdown("""
    <div class="sr-disclaimer">
        <span class="sr-disclaimer-icon">⚠</span>
        <p><strong>AI Output — Human Verification Required.</strong>
        Results are generated by a Large Language Model and may contain errors.
        Always verify findings against the original publication using the
        source links in each article panel.</p>
    </div>
    """, unsafe_allow_html=True)


# ── Cache helpers ──────────────────────────────────────────────────────────────

def _ck(review_id, pmid, task):
    return f"ai_{review_id}_{pmid}_{task}"

def _get_cached(review_id, pmid, task):
    return st.session_state.get(_ck(review_id, pmid, task))

def _set_cached(review_id, pmid, task, value):
    st.session_state[_ck(review_id, pmid, task)] = value

def _clear_task_cache(review_id, articles, task):
    for a in articles:
        key = _ck(review_id, a["pmid"], task)
        if key in st.session_state:
            del st.session_state[key]


# ── DOI / source link helper ───────────────────────────────────────────────────

def _article_links_md(article: dict) -> str:
    """Return HTML link badges for an article."""
    links = []
    doi = article.get("doi") or ""
    if doi:
        doi_clean = doi.strip()
        for prefix in ("https://doi.org/", "http://doi.org/", "doi:"):
            if doi_clean.lower().startswith(prefix.lower()):
                doi_clean = doi_clean[len(prefix):]
                break
        links.append(
            f'<a href="https://doi.org/{doi_clean.strip()}" target="_blank" ' +
            'class="sr-article-links"><span class="sr-link-doi">⊞ DOI</span></a>'
        )

    source = str(article.get("source") or "")
    pmid   = article.get("pmid") or ""
    if source == "pubmed" and pmid and not pmid.startswith("EPMC:"):
        links.append(
            f'<a href="https://pubmed.ncbi.nlm.nih.gov/{pmid}/" target="_blank">' +
            '<span class="sr-link-pubmed">PubMed ↗</span></a>'
        )

    url = article.get("url") or ""
    if "europepmc" in url:
        links.append(
            f'<a href="{url}" target="_blank">' +
            '<span class="sr-link-epmc">Europe PMC ↗</span></a>'
        )

    if not links:
        return ""
    return ('<div class="sr-article-links" style="display:flex;flex-wrap:wrap;gap:0.35rem;margin-top:0.4rem;">' +
            "".join(links) + "</div>")


def _render_article_links(article: dict) -> None:
    """Render styled article link badges via st.markdown."""
    html = _article_links_md(article)
    if html:
        st.markdown(html, unsafe_allow_html=True)


# ── Consensus logic ────────────────────────────────────────────────────────────

def _get_consensus_decision(review_id, pmid):
    adj = adjudication_repo.get_adjudication(review_id, pmid)
    if adj and adj.get("final_decision"):
        return adj["final_decision"]
    all_decs = screening_repo.get_all_decisions_for_article(
        review_id, pmid, "title_abstract"
    )
    primary = {k: v for k, v in all_decs.items() if k not in SYSTEM_REVIEWER_IDS}
    if not primary:
        return None
    unique = set(primary.values())
    return unique.pop() if len(unique) == 1 else None

def _get_included_articles(review_id, all_articles):
    """Return articles included at Stage 2 if any exist, else Stage 1 included."""
    # Check if Stage 2 screening has started
    s2_pmids = article_repo.get_stage1_included_pmids(review_id)
    if s2_pmids:
        # Use Stage 2 included if Stage 2 decisions exist
        s2_counts = article_repo.get_stage2_counts(review_id)
        if s2_counts.get("s2_included", 0) + s2_counts.get("s2_excluded", 0) > 0:
            # Stage 2 has decisions — use Stage 2 included
            s2_included_pmids = set()
            for pmid in s2_pmids:
                all_s2 = screening_repo.get_all_decisions_for_article(
                    review_id, pmid, "full_text")
                primary = {k:v for k,v in all_s2.items() if k not in SYSTEM_REVIEWER_IDS}
                if primary and set(primary.values()) == {"include"}:
                    s2_included_pmids.add(pmid)
            if s2_included_pmids:
                return [a for a in all_articles if a["pmid"] in s2_included_pmids]
    # Fall back to Stage 1 included
    return [a for a in all_articles
            if _get_consensus_decision(review_id, a["pmid"]) == "include"]

def _count_pending(review_id, all_articles):
    count = 0
    for a in all_articles:
        all_decs = screening_repo.get_all_decisions_for_article(
            review_id, a["pmid"], "title_abstract"
        )
        primary = {k: v for k, v in all_decs.items() if k not in SYSTEM_REVIEWER_IDS}
        if len(primary) == 0:
            count += 1
    return count


# ── Main entry point ───────────────────────────────────────────────────────────

def render_ai_analysis_panel(review_id: int) -> None:
    all_articles = article_repo.get_articles_for_review(review_id)
    if not all_articles:
        st.info("📋 No articles found. Run a search first (Search tab).")
        return

    included  = _get_included_articles(review_id, all_articles)
    n_total   = len(all_articles)
    n_incl    = len(included)
    n_pending = _count_pending(review_id, all_articles)
    db_counts = article_repo.get_screening_counts(review_id)
    n_conflict= db_counts.get("conflict", 0)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Articles", n_total)
    c2.metric("✅ Included",    n_incl)
    c3.metric("⏳ Pending",     n_pending)
    c4.metric("⚠️ Conflicts",   n_conflict)

    if n_pending > 0:
        st.warning(f"⚠️ **{n_pending}** article(s) not yet screened. "
                   "Complete screening first.")
    if n_conflict > 0:
        st.warning(f"⚠️ **{n_conflict}** conflict(s) unresolved. "
                   "Switch to **Editor** → Screening → Conflicts to resolve.")

    if n_incl == 0:
        st.info("No articles included yet. Go to **Screening** and mark articles as Include.")
        return

    st.markdown(f"""
    <div style="display:flex;align-items:center;gap:0.75rem;
                background:var(--emerald-light,#D1FAE5);
                border:1px solid rgba(5,150,105,0.25);
                border-left:3px solid #059669;
                border-radius:10px;padding:0.75rem 1rem;margin-bottom:1rem;">
        <span style="font-size:1.1rem;">✓</span>
        <div>
            <span style="font-weight:600;color:#065F46;font-size:0.9rem;">
                {n_incl} article{'s' if n_incl != 1 else ''} included
            </span>
            <span style="color:#047857;font-size:0.82rem;margin-left:0.5rem;">
                · Meta-analysis preparation · PICO/Summary available in Screening tabs
            </span>
        </div>
    </div>
    """, unsafe_allow_html=True)
    st.divider()

    st.info(
        "💡 **PICO Extraction** is available per-article in **Stage 1 Screening**. "
        "**Full-text Summarisation** is available per-article in **Stage 2 Screening**. "
        "This tab focuses on post-inclusion meta-analysis preparation."
    )

    (tab_pool, tab_rob, tab_grade) = st.tabs([
        "📊 Data Pooling",
        "⚖️ Risk of Bias",
        "📋 GRADE / SoF",
    ])

    with tab_pool:
        _tab_data_pool(review_id, included)
    with tab_rob:
        _tab_risk_of_bias(review_id, included)
    with tab_grade:
        _tab_grade(review_id, included)


# ── Data Pooling ───────────────────────────────────────────────────────────────

def _tab_data_pool(review_id, articles):
    st.markdown('''<div class="sr-section-header">
      <div class="sr-section-icon" style="background:#F5F3FF;">📊</div>
      <div><h3 style="color:var(--ink,#0F172A);">Data Pooling for Meta-Analysis</h3>
           <p style="font-size:0.78rem;color:var(--ink-40,#64748B);margin:0;">
           Structured extraction: sample size, effect size, outcomes, adverse events</p>
      </div></div>''', unsafe_allow_html=True)
    _render_ai_disclaimer()

    with st.expander("ℹ️ Fields extracted", expanded=False):
        st.markdown(
            "Sample size · Age group · Sex · Severity/baseline · "
            "Intervention · Comparator · Follow-up · Primary outcome + result · "
            "Secondary outcomes · Adverse events · Statistical significance · "
            "Study design · Country/setting"
        )

    c1, c2 = st.columns([2, 1])
    run_all = c1.button("▶ Extract Data from All", key="pool_all", type="primary")
    if c2.button("🔄 Clear & Retry", key="pool_clear"):
        _clear_task_cache(review_id, articles, "data_pool")
        st.rerun()

    missing_abstract = 0
    ran_any          = False

    for article in articles:
        pmid     = article["pmid"]
        abstract = article.get("abstract", "")
        title    = article.get("title", "")
        cached   = _get_cached(review_id, pmid, "data_pool")
        links_md = _article_links_md(article)
        if not abstract:
            missing_abstract += 1

        with st.expander(f"**{title[:80]}**", expanded=False):
            meta_line = f"PMID: `{pmid}` · {article.get('journal','')} {article.get('year','')}"
            st.caption(meta_line)
            if links_md:
                st.markdown(links_md, unsafe_allow_html=True)
            if not abstract:
                st.warning("No abstract — extraction will produce minimal data.")

            run_one = st.button("Extract Data", key=f"pool_{pmid}")
            if (run_all or run_one) and not cached:
                with st.spinner("Extracting structured data…"):
                    try:
                        sd = extract_study_data(abstract, pmid=pmid, title=title)
                        _set_cached(review_id, pmid, "data_pool", sd)
                        ran_any = True
                    except Exception as e:
                        logger.error("Data pool error PMID %s: %s", pmid, e)
                        st.error(f"Extraction error: {e}")

            sd = _get_cached(review_id, pmid, "data_pool")
            if sd:
                row  = sd.to_table_row()
                keys = [k for k in row if k not in ("PMID", "Title")]
                cols = st.columns(2)
                for i, k in enumerate(keys):
                    cols[i % 2].markdown(f"**{k}:** {row[k] or '—'}")

    if missing_abstract > 0:
        st.warning(f"⚠️ {missing_abstract} article(s) have no abstract.")

    all_sd: List[StudyData] = []
    for a in articles:
        sd = _get_cached(review_id, a["pmid"], "data_pool")
        if sd:
            all_sd.append(sd)

    if all_sd:
        st.divider()
        st.markdown(f"#### 📋 Composite Table ({len(all_sd)}/{len(articles)} studies)")
        df = pd.DataFrame(build_composite_table(all_sd))
        doi_map = {a["pmid"]: (a.get("doi") or "") for a in articles}
        if "PMID" in df.columns:
            df.insert(2, "DOI", df["PMID"].map(lambda p: doi_map.get(p, "")))
        st.dataframe(df, use_container_width=True, hide_index=True)
        c1_, c2_ = st.columns(2)
        with c1_:
            st.download_button("📥 CSV", data=df.to_csv(index=False),
                               file_name=f"data_pooling_{review_id}.csv",
                               mime="text/csv", use_container_width=True)
        with c2_:
            st.download_button("📥 JSON",
                               data=json.dumps([sd.to_dict() for sd in all_sd], indent=2),
                               file_name=f"data_pooling_{review_id}.json",
                               mime="application/json", use_container_width=True)
        st.divider()
        _pool_summary(df)

    if run_all and ran_any:
        st.rerun()


def _pool_summary(df):
    st.markdown("#### Quick Summary")
    c1, c2, c3 = st.columns(3)
    if "Study Design" in df.columns:
        designs = df["Study Design"].value_counts()
        c1.markdown("**Study Designs:**")
        for d, n in designs.items():
            c1.markdown(f"- {d}: **{n}**")
    if "Primary Result" in df.columns:
        reported = (df["Primary Result"] != "Not reported").sum()
        c2.metric("Outcomes Reported", f"{reported}/{len(df)}")
    if "Comparator" in df.columns:
        c2.metric("Comparator Available",
                  (df["Comparator"] != "Not reported").sum())
    if "Country/Setting" in df.columns:
        countries = df["Country/Setting"].value_counts().head(5)
        c3.markdown("**Top Countries:**")
        for country, n in countries.items():
            c3.markdown(f"- {country}: **{n}**")


# ══════════════════════════════════════════════════════════════════════════════
# ⚖️  RISK OF BIAS TAB (NEW)
# ══════════════════════════════════════════════════════════════════════════════

def _tab_risk_of_bias(review_id, articles):
    st.markdown('''<div class="sr-section-header">
      <div class="sr-section-icon" style="background:#FFF0F0;">⚖️</div>
      <div><h3 style="color:var(--ink,#0F172A);">Risk of Bias Assessment</h3>
      </div></div>''', unsafe_allow_html=True)
    st.caption(
        "**RCTs** → Cochrane RoB 2 (5 domains, Low / Some concerns / High risk)  |  "
        "**Cohort/CC/XS** → Newcastle-Ottawa Scale (star system, max 9–10 stars)"
    )
    _render_ai_disclaimer()

    with st.expander("ℹ️ How to interpret results", expanded=False):
        st.markdown("""
**RoB 2 (RCTs):** 5 domains, each rated 🟢 Low / 🟡 Some concerns / 🔴 High risk.
Overall: 🔴 if any domain High, or ≥3 domains Some concerns; 🟡 if any Some concerns; 🟢 if all Low.

**NOS (Observational):** Star awards per criterion. ⭐⭐⭐⭐⭐⭐⭐ = 7+ Good · 5-6 Fair · <5 Poor.
Three versions: Cohort (max 9★) · Case-control (max 9★) · Cross-sectional NOS-xs2 (max 10★).

**Why both tools?** RoB 2 and NOS assess different aspects of different study designs.
Using the correct tool for each study is required by PRISMA 2020 and Cochrane guidelines.

**Study classification** is automatic but you should verify it — the tool applied depends on it.
""")

    c1, c2 = st.columns([2, 1])
    run_all = c1.button("▶ Assess All Articles", key="rob_all", type="primary")
    if c2.button("🔄 Clear All RoB", key="rob_clear"):
        for a in articles:
            for t in ("study_class", "rob2", "nos"):
                k = _ck(review_id, a["pmid"], t)
                if k in st.session_state:
                    del st.session_state[k]
        st.rerun()

    ran_any = False

    for article in articles:
        pmid     = article["pmid"]
        abstract = article.get("abstract", "")
        title    = article.get("title", "")
        links_md = _article_links_md(article)

        # ── Step 1: Classify study design ─────────────────────────────────────
        clf = _get_cached(review_id, pmid, "study_class")
        if (run_all or False) and not clf:
            clf = classify_study(
                abstract=abstract, title=title,
                pub_types=_get_pub_types(article),
            )
            _set_cached(review_id, pmid, "study_class", clf)
            ran_any = True
        elif not clf:
            clf = None

        # Determine expander icon
        rob_result = _get_cached(review_id, pmid, "rob2")
        nos_result = _get_cached(review_id, pmid, "nos")
        if rob_result:
            icon = RISK_EMOJI.get(rob_result.overall, "⬜")
        elif nos_result:
            icon = nos_result.quality_emoji
        elif clf:
            icon = clf.emoji
        else:
            icon = "⬜"

        with st.expander(f"{icon} **{title[:80]}**", expanded=False):
            meta_line = f"PMID: `{pmid}` · {article.get('journal','')} {article.get('year','')}"
            st.caption(meta_line)
            if links_md:
                st.markdown(links_md, unsafe_allow_html=True)

            # Run button (per-article)
            run_one = st.button("Assess this article", key=f"rob_{pmid}")

            if (run_all or run_one) and not clf:
                clf = classify_study(
                    abstract=abstract, title=title,
                    pub_types=_get_pub_types(article),
                )
                _set_cached(review_id, pmid, "study_class", clf)
                ran_any = True

            if clf:
                # Show study design classification
                c_des, c_conf = st.columns([3, 1])
                c_des.markdown(
                    f"**Study design:** {clf.emoji} {clf.display_design}"
                )
                conf_colour = {"high": "🟢", "moderate": "🟡", "low": "🔴"}.get(
                    clf.confidence, "⬜"
                )
                c_conf.markdown(
                    f"**Confidence:** {conf_colour} {clf.confidence.capitalize()}"
                )
                if clf.signals:
                    st.caption("Signals: " + " · ".join(clf.signals[:3]))

                # ── RoB 2 (for RCTs and quasi-experimental) ───────────────────
                if clf.rob_tool == "rob2":
                    rob2 = _get_cached(review_id, pmid, "rob2")
                    if (run_all or run_one) and not rob2:
                        with st.spinner("Running RoB 2…"):
                            ft = _get_full_text(article)
                            rob2 = assess_rob2(abstract, ft)
                            _set_cached(review_id, pmid, "rob2", rob2)
                            ran_any = True

                    if rob2:
                        _render_rob2(rob2)

                # ── NOS (for observational studies) ───────────────────────────
                elif clf.rob_tool in ("nos_cohort", "nos_case_control",
                                     "nos_cross_sectional"):
                    nos = _get_cached(review_id, pmid, "nos")
                    if (run_all or run_one) and not nos:
                        with st.spinner(f"Running NOS ({clf.rob_tool})…"):
                            ft = _get_full_text(article)
                            nos = assess_nos(abstract, clf.rob_tool, ft)
                            _set_cached(review_id, pmid, "nos", nos)
                            ran_any = True

                    if nos:
                        _render_nos(nos)

                elif clf.rob_tool is None:
                    if clf.design == StudyDesign.REVIEW:
                        st.info("📚 Systematic review / meta-analysis — "
                                "quality assessed using AMSTAR-2 (not yet implemented). "
                                "Use the ⭐ Data Pooling tab for structured extraction.")
                    else:
                        st.info(f"No standardised RoB tool applies to {clf.display_design}. "
                                "Use the ⭐ Data Pooling tab for structured extraction.")
            else:
                if not run_all and not run_one:
                    st.caption("Click 'Assess this article' or '▶ Assess All' to run.")

    # ── Summary table ──────────────────────────────────────────────────────────
    rob_rows, nos_rows = [], []
    for a in articles:
        clf = _get_cached(review_id, a["pmid"], "study_class")
        rob = _get_cached(review_id, a["pmid"], "rob2")
        nos = _get_cached(review_id, a["pmid"], "nos")

        if rob:
            row = {"PMID": a["pmid"], "Title": a["title"][:50],
                   "DOI": a.get("doi") or "",
                   "Design": clf.display_design if clf else "RCT"}
            for dom in rob.domains:
                row[dom.name] = f"{dom.emoji} {dom.label}"
            row["Overall"] = f"{rob.overall_emoji} {rob.overall_label}"
            row["Rationale"] = rob.overall_rationale
            rob_rows.append(row)

        if nos:
            nos_rows.append({
                "PMID": a["pmid"], "Title": a["title"][:50],
                "DOI": a.get("doi") or "",
                "Design": clf.display_design if clf else nos.instrument,
                "Selection": f"{nos.selection.stars}/{nos.selection.max_stars}★",
                "Comparability": f"{nos.comparability.stars}/{nos.comparability.max_stars}★",
                "Outcome/Exposure": f"{nos.outcome.stars}/{nos.outcome.max_stars}★",
                "Total": f"{nos.total_stars}/{nos.max_stars}★",
                "Grade": f"{nos.quality_emoji} {nos.quality_label}",
            })

    if rob_rows:
        st.divider()
        st.markdown(f"#### RoB 2 Summary ({len(rob_rows)} RCTs)")
        df_rob = pd.DataFrame(rob_rows)
        st.dataframe(df_rob, use_container_width=True, hide_index=True)
        st.download_button("📥 Export RoB 2 (CSV)",
                           data=df_rob.to_csv(index=False),
                           file_name=f"rob2_{review_id}.csv", mime="text/csv")

    if nos_rows:
        st.divider()
        st.markdown(f"#### NOS Summary ({len(nos_rows)} observational studies)")
        df_nos = pd.DataFrame(nos_rows)
        st.dataframe(df_nos, use_container_width=True, hide_index=True)
        st.download_button("📥 Export NOS (CSV)",
                           data=df_nos.to_csv(index=False),
                           file_name=f"nos_{review_id}.csv", mime="text/csv")

    if run_all and ran_any:
        st.rerun()


def _render_rob2(rob2) -> None:
    """Display RoB 2 result in article expander."""
    st.markdown(
        f"**Overall RoB 2:** {rob2.overall_emoji} **{rob2.overall_label}**"
    )
    st.caption(rob2.overall_rationale)

    cols = st.columns(5)
    for col, dom in zip(cols, rob2.domains):
        col.markdown(
            f"<div style='text-align:center'>"
            f"<small>{dom.name.split(':')[0]}</small><br>"
            f"<span style='font-size:1.4em'>{dom.emoji}</span><br>"
            f"<small>{dom.label}</small></div>",
            unsafe_allow_html=True,
        )
    with st.expander("🔍 Signalling questions detail", expanded=False):
        for dom in rob2.domains:
            st.markdown(f"**{dom.name}** — {dom.emoji} {dom.label}")
            for sig in dom.signals:
                st.caption(f"  · {sig}")
            if dom.rationale:
                st.caption(f"  → {dom.rationale}")


def _render_nos(nos) -> None:
    """Display NOS result in article expander."""
    instrument_label = {
        "nos_cohort":           "NOS Cohort",
        "nos_case_control":     "NOS Case-Control",
        "nos_cross_sectional":  "NOS-xs2 Cross-Sectional",
    }.get(nos.instrument, nos.instrument)

    st.markdown(
        f"**{instrument_label}:** {nos.quality_emoji} **{nos.quality_label}** "
        f"— {nos.total_stars}/{nos.max_stars} stars  {nos.star_display}"
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Selection",
              f"{nos.selection.stars}/{nos.selection.max_stars}★")
    c2.metric("Comparability",
              f"{nos.comparability.stars}/{nos.comparability.max_stars}★")
    c3.metric("Outcome/Exposure",
              f"{nos.outcome.stars}/{nos.outcome.max_stars}★")

    with st.expander("🔍 Item detail", expanded=False):
        for domain in [nos.selection, nos.comparability, nos.outcome]:
            st.markdown(f"**{domain.name}**")
            for item in domain.items:
                st.caption(f"  {item}")


# ══════════════════════════════════════════════════════════════════════════════
# 📋  GRADE / SoF TAB (NEW)
# ══════════════════════════════════════════════════════════════════════════════

def _tab_grade(review_id, articles):
    st.markdown('''<div class="sr-section-header">
      <div class="sr-section-icon" style="background:#F0FDF4;">📋</div>
      <div><h3 style="color:var(--ink,#0F172A);">GRADE Certainty of Evidence</h3>
      </div></div>''', unsafe_allow_html=True)
    st.caption(
        "GRADE operates across **all included studies** for a specific outcome. "
        "Run ⚖️ Risk of Bias and 📊 Data Pooling first for best results."
    )
    _render_ai_disclaimer()

    with st.expander("ℹ️ GRADE certainty levels", expanded=False):
        st.markdown("""
| Symbol | Level | Meaning |
|--------|-------|---------|
| ⊕⊕⊕⊕ | **High** | Further research unlikely to change our confidence |
| ⊕⊕⊕◯ | **Moderate** | Further research likely to have important impact |
| ⊕⊕◯◯ | **Low** | Further research very likely to change the estimate |
| ⊕◯◯◯ | **Very Low** | Very little confidence in the effect estimate |

**Starting certainty:** RCTs → High · Observational studies → Low

**Downgrade factors:** Risk of bias · Inconsistency · Indirectness · Imprecision · Publication bias

**Upgrade factors (observational only):** Large effect · Dose-response relationship
""")

    # ── Outcome configuration ──────────────────────────────────────────────────
    st.markdown("#### Configure GRADE Assessment")
    col_out, col_design = st.columns(2)
    with col_out:
        outcome_name = st.text_input(
            "Outcome to grade",
            value="Primary outcome",
            help="e.g. 'Overall survival', 'Complete remission rate', 'Adverse events'"
        )
    with col_design:
        predominant_design = st.selectbox(
            "Predominant study design",
            ["rct", "observational"],
            format_func=lambda x: "RCTs (start: High certainty)" if x == "rct"
                                  else "Observational (start: Low certainty)",
        )

    grade_key = f"grade_{review_id}"

    if st.button("▶ Run GRADE Assessment", type="primary", key="grade_run"):
        # Gather cached RoB assessments
        rob2_list = [r for a in articles
                     if (r := _get_cached(review_id, a["pmid"], "rob2")) is not None]
        nos_list  = [n for a in articles
                     if (n := _get_cached(review_id, a["pmid"], "nos")) is not None]
        pool_list = [r for a in articles
                     if (sd := _get_cached(review_id, a["pmid"], "data_pool")) is not None
                     for r in [sd.to_table_row()]]

        if not rob2_list and not nos_list:
            st.warning(
                "⚠️ No Risk of Bias assessments found. "
                "Run the ⚖️ Risk of Bias tab first for accurate GRADE results. "
                "Proceeding with limited information."
            )

        with st.spinner("Computing GRADE certainty…"):
            try:
                grade = assess_grade(
                    rob2_assessments=rob2_list,
                    nos_assessments=nos_list,
                    pooled_data=pool_list,
                    outcome=outcome_name,
                    study_design=predominant_design,
                )
                st.session_state[grade_key] = grade
            except Exception as e:
                logger.error("GRADE assessment failed: %s", e)
                st.error(f"GRADE error: {e}")

    if st.button("🔄 Clear GRADE", key="grade_clear"):
        st.session_state.pop(grade_key, None)
        st.rerun()

    # ── Display GRADE result ───────────────────────────────────────────────────
    grade = st.session_state.get(grade_key)
    if grade:
        st.divider()

        # Main certainty banner
        emoji = CERTAINTY_EMOJI.get(grade.final_certainty, "⬜")
        display = CERTAINTY_DISPLAY.get(grade.final_certainty, grade.final_certainty)

        st.markdown(
            f"### {emoji} **{grade.outcome}** — Certainty: **{display}**"
        )
        st.info(grade.certainty_meaning)
        st.caption(f"Rationale: {grade.certainty_rationale}")

        # Summary metrics
        mc1, mc2, mc3, mc4 = st.columns(4)
        mc1.metric("Studies",       grade.n_studies)
        mc2.metric("Participants",  grade.n_participants or "NR")
        mc3.metric("Starting",      grade.starting_certainty.upper())
        mc4.metric("Final",         grade.final_certainty.replace("_", " ").upper())

        # Factor breakdown
        st.markdown("#### Downgrade / Upgrade Factors")
        factor_cols = st.columns(5)
        down_factors = [grade.risk_of_bias, grade.inconsistency,
                        grade.indirectness, grade.imprecision, grade.publication_bias]

        for col, factor in zip(factor_cols, down_factors):
            if factor.direction == "downgrade":
                icon = "🔴" if factor.levels == 2 else "🟡"
                label = f"↓{factor.levels}"
            elif factor.direction == "upgrade":
                icon = "🟢"
                label = f"↑{factor.levels}"
            else:
                icon = "🟢"
                label = "—"
            col.markdown(
                f"<div style='text-align:center'>"
                f"<small>{factor.name}</small><br>"
                f"<span style='font-size:1.3em'>{icon}</span><br>"
                f"<small>{label}</small></div>",
                unsafe_allow_html=True,
            )

        # Rationale details
        with st.expander("🔍 Factor rationales", expanded=False):
            for f in grade.all_factors:
                if f.direction != "none" and f.rationale:
                    dir_str = f"{'↓' * f.levels} Downgrade" if f.direction == "downgrade" \
                              else f"↑ Upgrade"
                    st.markdown(f"**{f.name}** — {dir_str}")
                    st.caption(f"  {f.rationale}")

        # Summary of Findings table
        st.divider()
        st.markdown("#### 📋 Summary of Findings (SoF) Table")
        st.caption("Standard Cochrane SoF format. Export for your systematic review.")
        sof_row = grade.to_sof_row()
        sof_df  = pd.DataFrame([sof_row])
        st.dataframe(sof_df, use_container_width=True, hide_index=True)

        c1_, c2_ = st.columns(2)
        with c1_:
            st.download_button(
                "📥 Export SoF (CSV)",
                data=sof_df.to_csv(index=False),
                file_name=f"grade_sof_{review_id}.csv",
                mime="text/csv",
                use_container_width=True,
            )
        with c2_:
            st.download_button(
                "📥 Export Full GRADE (JSON)",
                data=json.dumps(grade.to_export_dict(), indent=2),
                file_name=f"grade_{review_id}.json",
                mime="application/json",
                use_container_width=True,
            )

        # Reporting template
        st.divider()
        st.markdown("#### 📝 Reporting Template")
        st.caption("Copy this into your Methods / Results section.")
        template = (
            f"The certainty of evidence for {grade.outcome} was assessed using the GRADE approach. "
            f"Based on {grade.n_studies} {'randomised trial' if predominant_design == 'rct' else 'observational stud'}{'y' if grade.n_studies == 1 else 'ies'} "
            f"({grade.n_participants or 'N'} participants), the certainty of evidence was rated as "
            f"**{grade.final_certainty.replace('_', ' ')}** ({CERTAINTY_DISPLAY.get(grade.final_certainty, '')}). "
            f"{grade.certainty_rationale}"
        )
        st.code(template, language=None)


# ── Helper utilities ───────────────────────────────────────────────────────────

def _get_pub_types(article: dict) -> Optional[List[str]]:
    """Extract PubMed publication types from article venue field."""
    venue = article.get("venue") or ""
    if not venue:
        return None
    return [pt.strip() for pt in venue.split(";") if pt.strip()]


def _get_full_text(article: dict) -> str:
    """Get full text if available (stored in session_state by full-text pipeline)."""
    return ""   # Full text integration deferred — abstract is primary input
