# ui/ai_analysis_panel.py — v3
#
# CHANGES:
#   Added two new tabs:
#     ⚖️  Risk of Bias — RoB 2 (RCTs) / NOS (observational) per-article assessment
#     📋  GRADE / SoF   — GRADE certainty across all included studies + SoF table
#   Original four tabs unchanged.
#
# Architecture:
#   - study_classifier determines which RoB tool to apply per article
#   - rob2_assessor / nos_assessor run LLM signalling questions + deterministic algorithm
#   - grade_assessor aggregates across all studies for the overall evidence certainty
#   - All results cached in session_state (same pattern as existing tabs)






# ui/ai_analysis_panel.py — v3
#
# CHANGES:
#   Added two new tabs:
#     ⚖️  Risk of Bias — RoB 2 (RCTs) / NOS (observational) per-article assessment
#     📋  GRADE / SoF   — GRADE certainty across all included studies + SoF table
#   Original four tabs unchanged.
#
# Architecture:
#   - study_classifier determines which RoB tool to apply per article
#   - rob2_assessor / nos_assessor run LLM signalling questions + deterministic algorithm
#   - grade_assessor aggregates across all studies for the overall evidence certainty
#   - All results cached in session_state (same pattern as existing tabs)












# ui/ai_analysis_panel.py — v3
#
# CHANGES:
#   Added two new tabs:
#     ⚖️  Risk of Bias — RoB 2 (RCTs) / NOS (observational) per-article assessment
#     📋  GRADE / SoF   — GRADE certainty across all included studies + SoF table
#   Original four tabs unchanged.
#
# Architecture:
#   - study_classifier determines which RoB tool to apply per article
#   - rob2_assessor / nos_assessor run LLM signalling questions + deterministic algorithm
#   - grade_assessor aggregates across all studies for the overall evidence certainty
#   - All results cached in session_state (same pattern as existing tabs)

import json
import logging
from typing import Any, Dict, List, Optional
import re
import pandas as pd
import streamlit as st

from pipeline.data_pooler        import extract_study_data, build_composite_table, StudyData
from pipeline.study_classifier   import classify_study, StudyDesign
from pipeline.rob2_assessor      import assess_rob2, RISK_EMOJI, RISK_LABEL
from pipeline.nos_assessor       import assess_nos
from pipeline.grade_assessor     import (
    assess_grade, CERTAINTY_DISPLAY, CERTAINTY_EMOJI,
    CERTAINTY_MEANING, GRADEAssessment, GRADEFactor,
)
from storage.repository import (
    ArticleRepository, ScreeningRepository, AdjudicationRepository,
    AIAnalysisRepository,
)
from storage.repository import ArticleRepository as _AR  # for stage2 counts

logger = logging.getLogger(__name__)

article_repo      = ArticleRepository()
screening_repo    = ScreeningRepository()
adjudication_repo = AdjudicationRepository()
ai_repo           = AIAnalysisRepository()

SYSTEM_REVIEWER_IDS = {"final_resolved", "editor", "adjudicator"}


# ── AI Disclaimer ──────────────────────────────────────────────────────────────

def _render_ai_disclaimer() -> None:
    st.markdown("""
    <div class="sr-disclaimer">
        <span class="sr-disclaimer-icon">⚠</span>
        <p><strong>Note: This is an AI Output, Human Verification Required.</strong>
        Results are generated by a Large Language Model and may contain errors.
        Always verify findings against the original publication using the
        source links in each article panel.</p>
    </div>
    """, unsafe_allow_html=True)


# ── Cache helpers ──────────────────────────────────────────────────────────────

def _ck(review_id, pmid, task):
    return f"ai_{review_id}_{pmid}_{task}"

def _db_task(review_id, task):
    """Namespace task key by review_id to prevent cross-review contamination."""
    return f"r{review_id}_{task}"

def _get_cached(review_id, pmid, task):
    # 1. Check session_state first (fastest)
    val = st.session_state.get(_ck(review_id, pmid, task))
    if val is not None:
        return val
    # 2. Fall back to DB — use namespaced task key
    raw = ai_repo.get_analysis(pmid, _db_task(review_id, task))
    if raw is None:
        return None
    # 3. Reconstruct Python object from stored dict
    obj = _deserialise(task, raw)
    if obj is not None:
        st.session_state[_ck(review_id, pmid, task)] = obj
    return obj

def _set_cached(review_id, pmid, task, value):
    st.session_state[_ck(review_id, pmid, task)] = value
    # Persist to DB with namespaced key
    try:
        from dataclasses import asdict
        serialisable = asdict(value) if hasattr(value, '__dataclass_fields__') else value
        ai_repo.save_analysis(pmid, _db_task(review_id, task), serialisable)
    except Exception as e:
        logger.warning("Could not persist AI result to DB (task=%s): %s", task, e)

def _clear_task_cache(review_id, articles, task):
    for a in articles:
        key = _ck(review_id, a["pmid"], task)
        if key in st.session_state:
            del st.session_state[key]
        # Also clear from DB
        try:
            from storage.database import get_connection
            with get_connection() as conn:
                conn.execute(
                    "DELETE FROM ai_analyses WHERE pmid=? AND task=?",
                    (a["pmid"], _db_task(review_id, task)))
        except Exception:
            pass

def _deserialise(task: str, raw: Any) -> Any:
    """Reconstruct a dataclass object from a stored dict."""
    if not isinstance(raw, dict):
        return raw
    try:
        if task == "data_pool":
            from pipeline.data_pooler import StudyData
            return StudyData.from_dict(raw)
        if task == "rob2":
            from pipeline.rob2_assessor import RoB2Assessment, RoB2Domain
            def _rob2_domain(d):
                if not isinstance(d, dict):
                    return RoB2Domain(name="Unknown")
                return RoB2Domain(
                    name=d.get("name", ""),
                    judgement=d.get("judgement", "no_information"),
                    signals=d.get("signals", []),
                    rationale=d.get("rationale", ""),
                )
            return RoB2Assessment(
                d1_randomisation = _rob2_domain(raw.get("d1_randomisation", {})),
                d2_deviations    = _rob2_domain(raw.get("d2_deviations", {})),
                d3_missing_data  = _rob2_domain(raw.get("d3_missing_data", {})),
                d4_measurement   = _rob2_domain(raw.get("d4_measurement", {})),
                d5_reporting     = _rob2_domain(raw.get("d5_reporting", {})),
                overall          = raw.get("overall", "no_information"),
                overall_rationale= raw.get("overall_rationale", ""),
                notes            = raw.get("notes", ""),
            )
        if task in ("nos", "nos_cohort", "nos_cc", "nos_xs"):
            from pipeline.nos_assessor import NOSAssessment, NOSDomain
            def _nos_domain(d, default_name=""):
                if not isinstance(d, dict):
                    return NOSDomain(name=default_name)
                return NOSDomain(
                    name=d.get("name", default_name),
                    stars=d.get("stars", 0),
                    max_stars=d.get("max_stars", 0),
                    items=d.get("items", []),
                    rationale=d.get("rationale", ""),
                )
            return NOSAssessment(
                instrument   = raw.get("instrument", ""),
                selection    = _nos_domain(raw.get("selection", {}),    "Selection"),
                comparability= _nos_domain(raw.get("comparability", {}),"Comparability"),
                outcome      = _nos_domain(raw.get("outcome", {}),      "Outcome / Exposure"),
                total_stars  = raw.get("total_stars", 0),
                max_stars    = raw.get("max_stars", 9),
                quality_grade= raw.get("quality_grade", "poor"),
                notes        = raw.get("notes", ""),
            )
        if task in ("classify", "study_class"):
            from pipeline.study_classifier import StudyClassification
            return StudyClassification(**raw)
        if task in ("pico", "s1_pico"):
            from pipeline.pico_extractor import PICOResult
            return PICOResult(**raw)
        # summarize, grade — return raw dict/string as-is
        return raw
    except Exception as e:
        logger.warning("_deserialise failed for task=%s: %s", task, e)
        return None


# ── DOI / source link helper ───────────────────────────────────────────────────

def _article_links_md(article: dict) -> str:
    """Return HTML link badges for an article."""
    links = []
    doi = article.get("doi") or ""
    if doi:
        doi_clean = doi.strip()
        for prefix in ("https://doi.org/", "http://doi.org/", "doi:"):
            if doi_clean.lower().startswith(prefix.lower()):
                doi_clean = doi_clean[len(prefix):]
                break
        links.append(
            f'<a href="https://doi.org/{doi_clean.strip()}" target="_blank" ' +
            'class="sr-article-links"><span class="sr-link-doi">⊞ DOI</span></a>'
        )

    source = str(article.get("source") or "")
    pmid   = article.get("pmid") or ""
    if source == "pubmed" and pmid and not pmid.startswith("EPMC:"):
        links.append(
            f'<a href="https://pubmed.ncbi.nlm.nih.gov/{pmid}/" target="_blank">' +
            '<span class="sr-link-pubmed">PubMed ↗</span></a>'
        )

    url = article.get("url") or ""
    if "europepmc" in url:
        links.append(
            f'<a href="{url}" target="_blank">' +
            '<span class="sr-link-epmc">Europe PMC ↗</span></a>'
        )

    if not links:
        return ""
    return ('<div class="sr-article-links" style="display:flex;flex-wrap:wrap;gap:0.35rem;margin-top:0.4rem;">' +
            "".join(links) + "</div>")


def _render_article_links(article: dict) -> None:
    """Render styled article link badges via st.markdown."""
    html = _article_links_md(article)
    if html:
        st.markdown(html, unsafe_allow_html=True)


# ── Consensus logic ────────────────────────────────────────────────────────────

def _get_consensus_decision(review_id, pmid, stage="title_abstract"):
    adj = adjudication_repo.get_adjudication(review_id, pmid, stage=stage)
    if adj and adj.get("final_decision"):
        return adj["final_decision"]
    all_decs = screening_repo.get_all_decisions_for_article(
        review_id, pmid, stage)
    primary = {k: v for k, v in all_decs.items() if k not in SYSTEM_REVIEWER_IDS}
    if not primary:
        return None
    unique = set(primary.values())
    return unique.pop() if len(unique) == 1 else None

def _get_included_articles(review_id, all_articles):
    """Return Stage 2 included articles if Stage 2 has started, else Stage 1.
    Uses same adjudication-priority consensus logic as get_stage2_counts.
    """
    s2_counts = article_repo.get_stage2_counts(review_id)
    has_stage2 = (s2_counts.get("s2_included", 0) +
                  s2_counts.get("s2_excluded", 0)) > 0

    if has_stage2:
        # Mirror exactly what get_stage2_counts does — adjudication first,
        # then consensus — so the count here matches the dashboard metric.
        s2_pmids = article_repo.get_stage1_included_pmids(review_id)
        s2_included_pmids = set()
        for pmid in s2_pmids:
            dec = _get_consensus_decision(review_id, pmid, stage="full_text")
            if dec == "include":
                s2_included_pmids.add(pmid)
        return [a for a in all_articles if a["pmid"] in s2_included_pmids]

    # Fall back to Stage 1 included
    return [a for a in all_articles
    
            if _get_consensus_decision(review_id, a["pmid"]) == "include"]


def _count_pending(review_id, all_articles):
    count = 0
    for a in all_articles:
        all_decs = screening_repo.get_all_decisions_for_article(
            review_id, a["pmid"], "title_abstract"
        )
        primary = {k: v for k, v in all_decs.items() if k not in SYSTEM_REVIEWER_IDS}
        if len(primary) == 0:
            count += 1
    return count


# ── Main entry point ───────────────────────────────────────────────────────────


def render_ai_analysis_panel(review_id: int) -> None:
    all_articles = article_repo.get_articles_for_review(review_id)
    if not all_articles:
        st.info("📋 No articles found. Run a search first (Search tab).")
        return

    included  = _get_included_articles(review_id, all_articles)
    n_total   = len(all_articles)
    n_incl    = len(included)
    n_pending = _count_pending(review_id, all_articles)
    db_counts = article_repo.get_screening_counts(review_id)
    n_conflict= db_counts.get("conflict", 0)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Articles", n_total)
    c2.metric("✅ Included",    n_incl)
    c3.metric("⏳ Pending",     n_pending)
    c4.metric("⚠️ Conflicts",   n_conflict)

    if n_pending > 0:
        st.warning(f"⚠️ **{n_pending}** article(s) not yet screened. "
                   "Complete screening first.")
    if n_conflict > 0:
        st.warning(f"⚠️ **{n_conflict}** conflict(s) unresolved. "
                   "Switch to **Editor** → Screening → Conflicts to resolve.")

    if n_incl == 0:
        st.info("No articles included yet. Go to **Screening** and mark articles as Include.")
        return

    st.markdown(f"""
    <div style="display:flex;align-items:center;gap:0.75rem;
                background:var(--emerald-light,#D1FAE5);
                border:1px solid rgba(5,150,105,0.25);
                border-left:3px solid #059669;
                border-radius:10px;padding:0.75rem 1rem;margin-bottom:1rem;">
        <span style="font-size:1.1rem;">✓</span>
        <div>
            <span style="font-weight:600;color:#065F46;font-size:0.9rem;">
                {n_incl} article{'s' if n_incl != 1 else ''} included
            </span>
            <span style="color:#047857;font-size:0.82rem;margin-left:0.5rem;">
                · Meta-analysis preparation · PICO/Summary available in Screening tabs
            </span>
        </div>
    </div>
    """, unsafe_allow_html=True)
    st.divider()

    st.info(
        "💡 **PICO Extraction** is available per-article in **Stage 1 Screening**. "
        "**Full-text Summarisation** is available per-article in **Stage 2 Screening**. "
        "This tab focuses on post-inclusion meta-analysis preparation."
    )

    (tab_pool, tab_rob, tab_grade) = st.tabs([
        "📊 Data Pooling",
        "⚖️ Risk of Bias",
        "📋 GRADE / SoF",
    ])

    with tab_pool:
        _tab_data_pool(review_id, included)
    with tab_rob:
        try:
            _tab_risk_of_bias(review_id, included)
        except Exception as e:
            import traceback
            st.error(f"RoB error: {type(e).__name__}: {e}")
            st.code(traceback.format_exc())
    with tab_grade:
        _tab_grade(review_id, included)

# ── Forest plot helpers ────────────────────────────────────────────────────────

def _parse_effect_ci(text: str):
    """
    Parse (measure, estimate, ci_lo, ci_hi) from any result string.
    
    Rule: only attempts parsing when a recognised effect measure label
    is present (OR, HR, RR, MD, SMD etc.) — prevents false positives
    from survival times, percentages, and narrative text.
    Returns None when no valid measure+CI pair is found.
    """
    if not text or not text.strip():
        return None

    # Normalise unicode dashes, thin spaces, en-dashes
    text = (text.replace('\u2212', '-').replace('\u2013', '-')
                .replace('\u2014', '-').replace('\u2009', ' ')
                .replace('\u00a0', ' '))

    _NR = {"not reported", "nr", "na", "not applicable",
           "not available", "—", "-", "n/a", "none", ""}
    if text.strip().lower() in _NR:
        return None

    # ── Step 1: detect effect measure label (required) ────────────────
    _MEASURE_MAP = {
        "hazard ratio": "HR",  "adjusted hazard ratio": "HR",  "ahr": "HR",
        "odds ratio":   "OR",  "adjusted odds ratio":   "OR",  "aor": "OR",
        "risk ratio":   "RR",  "relative risk":         "RR",  "arr": "ARR",
        "mean difference": "MD", "standardised mean difference": "SMD",
        "standardized mean difference": "SMD",
        "risk difference": "RD",  "rate ratio": "RR",
        "irr": "IRR",
        # abbreviations
        "hr": "HR", "or": "OR", "rr": "RR", "md": "MD", "smd": "SMD",
        "rd": "RD",
    }
    measure = None
    m_pos   = len(text)    # position of measure label in text

    # Try long-form labels first (most specific)
    for label in sorted(_MEASURE_MAP, key=len, reverse=True):
        pat = re.compile(
            r'\b' + re.escape(label) + r'\b', re.IGNORECASE
        )
        m = pat.search(text)
        if m:
            measure = _MEASURE_MAP[label]
            m_pos   = m.end()
            break

    if not measure:
        return None    # no recognised effect measure → can't plot

    N = r'[-+]?\d+\.?\d*'   # number including negatives and decimals

    # ── Step 2: find estimate + CI using multiple pattern strategies ───

    # Pattern A: "1.76 (1.02 to 3.04)" — explicit "to"
    m = re.search(
        rf'({N})\s*\(\s*({N})\s+to\s+({N})\s*\)', text, re.IGNORECASE
    )
    if m:
        try:
            est, lo, hi = float(m.group(1)), float(m.group(2)), float(m.group(3))
            if lo < hi:
                return measure, est, lo, hi
        except ValueError:
            pass

    # Pattern B: "1.76 (1.02-3.04)" or "1.76 (1.02, 3.04)"
    m = re.search(rf'({N})\s*\(\s*({N})\s*[-,]\s*({N})\s*\)', text)
    if m:
        try:
            est, lo, hi = float(m.group(1)), float(m.group(2)), float(m.group(3))
            if lo < hi:
                return measure, est, lo, hi
        except ValueError:
            pass

    # Pattern C: "1.76, 95% CI[/confidence interval], 1.02-3.04"
    # Handles: "aHR 1.76, 95% confidence interval [CI], 1.02-3.04"
    m_ci = re.search(
        rf'(?:95%?\s*(?:confidence interval|CI)\s*[\[\(]?(?:CI)?\s*[\]\)]?'
        rf'[,\s]+)({N})\s*[-–,to]+\s*({N})',
        text, re.IGNORECASE
    )
    if m_ci:
        # Estimate is the number immediately after the measure label
        between = text[m_pos: m_ci.start()]
        m_e = re.search(rf'[=:\s,]?\s*({N})', between)
        if m_e:
            try:
                est = float(m_e.group(1))
                lo  = float(m_ci.group(1))
                hi  = float(m_ci.group(2))
                if lo < hi:
                    return measure, est, lo, hi
            except ValueError:
                pass

    # Pattern D: "95% CI: a to b" or "95% CI: a–b" anywhere in text
    m_ci2 = re.search(
        rf'95%?\s*CI[:\s]+({N})\s*(?:[-–]|to)\s*({N})',
        text, re.IGNORECASE
    )
    if m_ci2:
        before = text[:m_ci2.start()]
        m_e = re.search(rf'({N})\s*$', before.rstrip())
        if not m_e:
            m_e = re.search(rf'[=:\s]({N})', before[m_pos:])
        if m_e:
            try:
                est = float(m_e.group(1))
                lo  = float(m_ci2.group(1))
                hi  = float(m_ci2.group(2))
                if lo < hi:
                    return measure, est, lo, hi
            except ValueError:
                pass

    return None   # measure found but no parseable CI


_DESIGN_COLORS = {
    "rct":         "#3B82F6",   # blue
    "randomis":    "#3B82F6",
    "random":      "#3B82F6",
    "cohort":      "#8B5CF6",   # purple
    "case":        "#F59E0B",   # amber
    "cross":       "#10B981",   # green
    "observ":      "#06B6D4",   # cyan
}


def _design_color(design: str) -> str:
    d = (design or "").lower()
    for key, col in _DESIGN_COLORS.items():
        if key in d:
            return col
    return "#64748B"   # slate for unknown


def _render_forest_plot(all_sd: list, articles: list, review_id: int) -> None:
    """
    Render an interactive Plotly forest plot from extracted StudyData.
    Uses primary_outcome_result to parse effect size + 95% CI per study.
    """
    import plotly.graph_objects as go
    import plotly.io as pio

    # Build lookups from articles list
    year_map    = {a["pmid"]: str(a.get("year", "") or "")     for a in articles}
    author_map  = {a["pmid"]: (a.get("authors") or [])         for a in articles}

    def _label(pmid, idx):
        auths = author_map.get(pmid, [])
        year  = year_map.get(pmid, "")
        if auths and auths[0] and auths[0].strip():
            parts  = auths[0].split()
            name   = parts[-1] if len(parts) > 1 else parts[0]
            name   = name.rstrip(",")[:14]
        else:
            name = f"Study {idx + 1}"
        return f"{name} {year}".strip()

    # Parse studies
    parsed = []
    for idx, sd in enumerate(all_sd):
        result = _parse_effect_ci(sd.primary_outcome_result)
        if not result:
            continue
        measure, est, lo, hi = result

        # Sanity: CI valid + estimate within CI
        if lo >= hi:
            continue
        if measure in ("OR", "RR", "HR", "IRR", "AOR") and lo <= 0:
            continue
        if not (lo - 0.001 <= est <= hi + 0.001):
            continue

        # Sample size
        try:
            n_int = int(re.sub(r'[^\d]', '', str(sd.sample_size)))
        except (ValueError, TypeError):
            n_int = 0

        parsed.append({
            "label":   _label(sd.pmid, idx),
            "pmid":    sd.pmid,
            "measure": measure,
            "est":     est,
            "lo":      lo,
            "hi":      hi,
            "n":       n_int,
            "n_str":   sd.sample_size if sd.sample_size not in ("Not reported", "NR") else "NR",
            "design":  sd.study_design or "Not reported",
            "outcome": sd.primary_outcome or "",
            "result":  sd.primary_outcome_result or "",
        })

    n_total      = len(all_sd)
    n_no_result  = sum(1 for s in all_sd
                       if not s.primary_outcome_result
                       or s.primary_outcome_result.strip().lower()
                       in ("not reported", "nr", "none", "—", ""))
    n_no_measure = sum(1 for s in all_sd
                       if s.primary_outcome_result
                       and s.primary_outcome_result.strip().lower()
                       not in ("not reported", "nr", "none", "—", "")
                       and _parse_effect_ci(s.primary_outcome_result) is None)

    if not parsed:
        st.info(
            f"🌲 **Forest plot not available** — "
            f"{n_total} studies extracted, but none report a formal effect "
            f"measure (OR, HR, RR, MD, SMD) with a 95% confidence interval "
            f"in a parseable format.\n\n"
            f"- **{n_no_result}** studies: result not reported in abstract\n"
            f"- **{n_no_measure}** studies: result reported as percentage, "
            f"survival time, p-value, or narrative text (not plottable)\n\n"
            f"Forest plots require all studies to share a common effect "
            f"measure with CI. If the full texts contain formal statistics, "
            f"the Stage 2 data extraction may yield better results with a "
            f"stronger model."
        )
        return

    if len(parsed) < n_total:
        st.caption(
            f"ℹ️ Showing {len(parsed)} of {n_total} studies — "
            f"{n_total - len(parsed)} excluded (no parseable effect measure + CI). "
            f"Hover each point for full details."
        )

    # Warn if mixed measures
    measures = {p["measure"] for p in parsed}
    if len(measures) > 1:
        st.warning(
            f"⚠️ Mixed effect measures detected: {', '.join(measures)}. "
            "Forest plots should use a single measure. "
            "Review individual study results carefully."
        )

    # Axis type by dominant measure
    measure   = max(measures, key=lambda m: sum(1 for p in parsed if p["measure"] == m))
    use_log   = measure in ("OR", "RR", "HR", "IRR", "AOR")
    null_x    = 1.0 if use_log else 0.0

    n_studies = len(parsed)
    height    = max(380, n_studies * 52 + 130)

    # Marker size proportional to N (6–18 px)
    ns = [p["n"] for p in parsed if p["n"] > 0]
    n_min, n_max = (min(ns), max(ns)) if len(ns) > 1 else (0, 1)

    def _msize(n):
        if n <= 0 or n_max == n_min:
            return 10
        return int(6 + (n - n_min) / (n_max - n_min) * 12)

    fig = go.Figure()

    # ── Plot each study ────────────────────────────────────────────────
    seen_designs = {}

    for i, s in enumerate(parsed):
        y     = n_studies - 1 - i    # top-to-bottom
        color = _design_color(s["design"])
        lbl   = s["design"] if s["design"] != "Not reported" else "Unknown design"
        show_leg = lbl not in seen_designs
        if show_leg:
            seen_designs[lbl] = color

        # CI line
        fig.add_trace(go.Scatter(
            x=[s["lo"], s["hi"]], y=[y, y],
            mode="lines",
            line=dict(color=color, width=2.5),
            showlegend=False, hoverinfo="skip",
        ))
        # CI end caps
        fig.add_trace(go.Scatter(
            x=[s["lo"], s["hi"]], y=[y, y],
            mode="markers",
            marker=dict(symbol="line-ns-open", size=9,
                        color=color, line=dict(color=color, width=2.5)),
            showlegend=False, hoverinfo="skip",
        ))
        # Point estimate — square, sized by N
        fig.add_trace(go.Scatter(
            x=[s["est"]], y=[y],
            mode="markers",
            name=lbl,
            legendgroup=lbl,
            showlegend=show_leg,
            marker=dict(
                symbol="square",
                size=_msize(s["n"]),
                color=color,
                line=dict(color="white", width=1.5),
            ),
            hovertemplate=(
                f"<b>{s['label']}</b><br>"
                f"N = {s['n_str']}<br>"
                f"{s['measure']}: <b>{s['est']:.2f}</b> "
                f"(95% CI: {s['lo']:.2f} – {s['hi']:.2f})<br>"
                f"Design: {s['design']}<br>"
                f"Outcome: {s['outcome']}<br>"
                f"Result: {s['result']}<extra></extra>"
            ),
        ))

    # ── Null effect line ───────────────────────────────────────────────
    fig.add_vline(x=null_x,
                  line=dict(color="#94A3B8", width=1.5, dash="dot"))

    # ── Shading (ratio measures only) ──────────────────────────────────
    if use_log:
        all_x = [v for s in parsed for v in [s["lo"], s["hi"]]]
        x_min = min(all_x) * 0.6
        x_max = max(all_x) * 1.6
        fig.add_vrect(x0=x_min, x1=null_x,
                      fillcolor="#FEF2F2", opacity=0.25,
                      layer="below", line_width=0)
        fig.add_vrect(x0=null_x, x1=x_max,
                      fillcolor="#F0FDF4", opacity=0.25,
                      layer="below", line_width=0)

    # ── Right-side annotation panel (N | Effect CI) ────────────────────
    annotations = [
        dict(x=1.02, y=1.04, xref="paper", yref="paper",
             text="<b>N</b>", showarrow=False,
             font=dict(size=11, color="#0F172A"), xanchor="left"),
        dict(x=1.11, y=1.04, xref="paper", yref="paper",
             text=f"<b>{measure} (95% CI)</b>", showarrow=False,
             font=dict(size=11, color="#0F172A"), xanchor="left"),
    ]
    for i, s in enumerate(parsed):
        y_frac = (n_studies - 1 - i + 0.5) / n_studies
        annotations += [
            dict(x=1.02, y=y_frac, xref="paper", yref="paper",
                 text=s["n_str"], showarrow=False,
                 font=dict(size=10, color="#374151"), xanchor="left"),
            dict(x=1.11, y=y_frac, xref="paper", yref="paper",
                 text=f"{s['est']:.2f} ({s['lo']:.2f}–{s['hi']:.2f})",
                 showarrow=False,
                 font=dict(size=10, color="#374151"), xanchor="left"),
        ]

    # ── Axis labels ────────────────────────────────────────────────────
    if use_log:
        x_title = f"← Favours control    {measure}    Favours intervention →"
    else:
        x_title = f"← Favours control    {measure}    Favours intervention →"

    fig.update_layout(
        height=height,
        margin=dict(l=10, r=290, t=55, b=70),
        plot_bgcolor="white",
        paper_bgcolor="white",
        title=dict(
            text=(f"Forest Plot Preview — {measure} · "
                  f"{n_studies} {'study' if n_studies == 1 else 'studies'} · "
                  f"Square size ∝ sample size"),
            font=dict(size=13, color="#0F172A"),
            x=0.0, xanchor="left",
        ),
        xaxis=dict(
            title=dict(text=x_title, font=dict(size=11, color="#374151")),
            type="log" if use_log else "linear",
            gridcolor="#E2E8F0", gridwidth=1,
            zeroline=False, tickfont=dict(size=10),
            showgrid=True,
        ),
        yaxis=dict(
            tickvals=list(range(n_studies)),
            ticktext=[parsed[n_studies - 1 - i]["label"]
                      for i in range(n_studies)],
            tickfont=dict(size=11, color="#374151"),
            showgrid=False,
            range=[-0.6, n_studies - 0.4],
        ),
        annotations=annotations,
        legend=dict(
            orientation="h",
            yanchor="top", y=-0.12,
            xanchor="left", x=0,
            font=dict(size=10),
            title=dict(text="Study design  ", font=dict(size=10)),
        ),
        hovermode="closest",
    )

    st.plotly_chart(fig, use_container_width=True)

    # ── Download as self-contained interactive HTML ────────────────────
    _html = pio.to_html(fig, include_plotlyjs="cdn", full_html=True)
    st.download_button(
        "📥 Download Forest Plot (interactive HTML)",
        data=_html,
        file_name=f"forest_plot_{review_id}.html",
        mime="text/html",
    )



# ── Data Pooling ───────────────────────────────────────────────────────────────

def _tab_data_pool(review_id, articles):
    st.markdown('''<div class="sr-section-header">
      <div class="sr-section-icon" style="background:#F5F3FF;">📊</div>
      <div><h3 style="color:var(--ink,#0F172A);">Data Pooling for Meta-Analysis</h3>
           <p style="font-size:0.78rem;color:var(--ink-40,#64748B);margin:0;">
           Structured extraction: sample size, effect size, outcomes, adverse events</p>
      </div></div>''', unsafe_allow_html=True)
    _render_ai_disclaimer()

    with st.expander("ℹ️ Fields extracted", expanded=False):
        st.markdown(
            "Sample size · Age group · Sex · Severity/baseline · "
            "Intervention · Comparator · Follow-up · Primary outcome + result · "
            "Secondary outcomes · Adverse events · Statistical significance · "
            "Study design · Country/setting"
        )

    c1, c2 = st.columns([2, 1])
    run_all = c1.button("▶ Extract Data from All", key=f"pool_all_{review_id}", type="primary")
    if c2.button("🔄 Clear & Retry", key=f"pool_clear_{review_id}"):
        _clear_task_cache(review_id, articles, "data_pool")


    missing_abstract = 0
    ran_any          = False

    for article in articles:
        pmid     = article["pmid"]
        abstract = article.get("abstract", "")
        title    = article.get("title", "")
        cached   = _get_cached(review_id, pmid, "data_pool")
        links_md = _article_links_md(article)
        if not abstract:
            missing_abstract += 1

        with st.expander(f"**{title[:80]}**", expanded=False):
            meta_line = f"PMID: `{pmid}` · {article.get('journal','')} {article.get('year','')}"
            st.caption(meta_line)
            if links_md:
                st.markdown(links_md, unsafe_allow_html=True)
            if not abstract:
                st.warning("No abstract — extraction will produce minimal data.")

            run_one = st.button("Extract Data", key=f"pool_{pmid}")

            if (run_all or run_one) and not cached:
                with st.spinner("Extracting structured data…"):
                    try:
                        # Get full text if available for page-level anchoring
                        _ft = article_repo.get_full_text(pmid) or ""
                        sd = extract_study_data(abstract, pmid=pmid, title=title, full_text=_ft)
                        _set_cached(review_id, pmid, "data_pool", sd)
                        ran_any = True
                    except Exception as e:
                        logger.error("Data pool error PMID %s: %s", pmid, e)
                        st.error(f"Extraction error: {e}")

            sd = _get_cached(review_id, pmid, "data_pool")
            if sd:
                row     = sd.to_table_row()
                anchors = getattr(sd, "_anchors", {})
                keys    = [k for k in row if k not in ("PMID","Title")]

                # Field name → anchor key mapping
                _field_map = {
                    "N":               "sample_size",
                    "Primary Result":  "primary_outcome_result",
                    "Significance":    "statistical_significance",
                    "Follow-up":       "follow_up_duration",
                    "Adverse Events":  "adverse_events",
                    "Intervention":    "intervention",
                    "Comparator":      "comparator",
                    "Primary Outcome": "primary_outcome",
                }

                cols = st.columns(2)
                for i, k in enumerate(keys):
                    val    = row[k] or "—"
                    anchor = anchors.get(_field_map.get(k, ""))
                    if anchor and anchor.sentence_no > 0:
                        cite = anchor.citation()
                        conf = anchor.confidence_label()
                        cols[i % 2].markdown(
                            f"**{k}:** {val}  "
                            f"<span style='font-size:0.72rem;color:#6B7280;"
                            f"background:#F0FDF4;border:1px solid #BBF7D0;"
                            f"border-radius:4px;padding:1px 5px;margin-left:4px;'>"
                            f"{conf} · {cite}</span>",
                            unsafe_allow_html=True
                        )
                        if anchor.method == "fuzzy":
                            cols[i % 2].caption(
                                f"  ↳ *\"{anchor.sentence[:120]}…\"*"
                                if len(anchor.sentence) > 120
                                else f"  ↳ *\"{anchor.sentence}\"*"
                            )
                    else:
                        cols[i % 2].markdown(
                            f"**{k}:** {val}  "
                            f"<span style='font-size:0.72rem;color:#9B9B9A;"
                            f"background:#F9F9F8;border:1px solid #E5E5E3;"
                            f"border-radius:4px;padding:1px 5px;margin-left:4px;'>"
                            f"❌ Not located</span>",
                            unsafe_allow_html=True
                        )

                # Show numbered sentences for manual verification
                sentences = getattr(sd, "_sentences", None)
                if sentences:
                    with st.expander(
                        "🔍 Source sentences (for manual verification)",
                        expanded=False
                    ):
                        for si, sent in enumerate(sentences, 1):
                            st.markdown(
                                f"<span style='color:#6B7280;font-size:0.72rem;"
                                f"font-weight:700;margin-right:6px;'>S{si}</span>"
                                f"<span style='font-size:0.83rem;'>{sent}</span>",
                                unsafe_allow_html=True
                            )

    if missing_abstract > 0:
        st.warning(f"⚠️ {missing_abstract} article(s) have no abstract.")

    all_sd: List[StudyData] = []
    for a in articles:
        sd = _get_cached(review_id, a["pmid"], "data_pool")
        if sd:
            all_sd.append(sd)

    if all_sd:
        st.divider()
        st.markdown(f"#### 📋 Composite Table ({len(all_sd)}/{len(articles)} studies)")
        df = pd.DataFrame(build_composite_table(all_sd))
        doi_map = {a["pmid"]: (a.get("doi") or "") for a in articles}
        if "PMID" in df.columns:
            df.insert(2, "DOI", df["PMID"].map(lambda p: doi_map.get(p, "")))
        st.dataframe(df, use_container_width=True, hide_index=True)
        c1_, c2_ = st.columns(2)
        with c1_:
            st.download_button("📥 CSV", data=df.to_csv(index=False),
                               file_name=f"data_pooling_{review_id}.csv",
                               mime="text/csv", use_container_width=True)
        with c2_:
            st.download_button("📥 JSON",
                               data=json.dumps([sd.to_dict() for sd in all_sd], indent=2),
                               file_name=f"data_pooling_{review_id}.json",
                               mime="application/json", use_container_width=True)
        st.divider()
        _pool_summary(df)

        # ── Forest Plot Preview ────────────────────────────────────────
        st.divider()
        st.markdown("#### 🌲 Forest Plot Preview")
        st.caption(
            "Parsed from 'Primary Result' field. "
            "Point estimates with 95% CI — square size proportional to N. "
            "This is a visual preview; use dedicated meta-analysis software "
            "for pooled estimates."
        )
        _render_forest_plot(all_sd, articles, review_id)

    if run_all and ran_any:
        st.rerun()


def _pool_summary(df):
    st.markdown("#### Quick Summary")
    c1, c2, c3 = st.columns(3)
    if "Study Design" in df.columns:
        designs = df["Study Design"].value_counts()
        c1.markdown("**Study Designs:**")
        for d, n in designs.items():
            c1.markdown(f"- {d}: **{n}**")
    if "Primary Result" in df.columns:
        reported = (df["Primary Result"] != "Not reported").sum()
        c2.metric("Outcomes Reported", f"{reported}/{len(df)}")
    if "Comparator" in df.columns:
        c2.metric("Comparator Available",
                  (df["Comparator"] != "Not reported").sum())
    if "Country/Setting" in df.columns:
        countries = df["Country/Setting"].value_counts().head(5)
        c3.markdown("**Top Countries:**")
        for country, n in countries.items():
            c3.markdown(f"- {country}: **{n}**")


# ══════════════════════════════════════════════════════════════════════════════
# ⚖️  RISK OF BIAS TAB (NEW)
# ══════════════════════════════════════════════════════════════════════════════

def _tab_risk_of_bias(review_id, articles):
    st.markdown('''<div class="sr-section-header">
      <div class="sr-section-icon" style="background:#FFF0F0;">⚖️</div>
      <div><h3 style="color:var(--ink,#0F172A);">Risk of Bias Assessment</h3>
      </div></div>''', unsafe_allow_html=True)
    st.caption(
        "**RCTs** → Cochrane RoB 2 (5 domains, Low / Some concerns / High risk)  |  "
        "**Cohort/CC/XS** → Newcastle-Ottawa Scale (star system, max 9–10 stars)"
    )
    _render_ai_disclaimer()

    with st.expander("ℹ️ How to interpret results", expanded=False):
        st.markdown("""
**RoB 2 (RCTs):** 5 domains, each rated 🟢 Low / 🟡 Some concerns / 🔴 High risk.
Overall: 🔴 if any domain High, or ≥3 domains Some concerns; 🟡 if any Some concerns; 🟢 if all Low.

**NOS (Observational):** Star awards per criterion. ⭐⭐⭐⭐⭐⭐⭐ = 7+ Good · 5-6 Fair · <5 Poor.
Three versions: Cohort (max 9★) · Case-control (max 9★) · Cross-sectional NOS-xs2 (max 10★).

**Why both tools?** RoB 2 and NOS assess different aspects of different study designs.
Using the correct tool for each study is required by PRISMA 2020 and Cochrane guidelines.

**Study classification** is automatic but you should verify it — the tool applied depends on it.
""")

    c1, c2 = st.columns([2, 1])
    run_all = c1.button("▶ Assess All Articles", key=f"rob_all_{review_id}", type="primary")
    if c2.button("🔄 Clear All RoB", key=f"rob_clear_{review_id}"):
        for a in articles:
            for t in ("study_class", "rob2", "nos"):
                k = _ck(review_id, a["pmid"], t)
                if k in st.session_state:
                    del st.session_state[k]


    ran_any = False

    for article in articles:
        pmid     = article["pmid"]
        abstract = article.get("abstract", "")
        title    = article.get("title", "")
        links_md = _article_links_md(article)

        # ── Step 1: Classify study design ─────────────────────────────────────
        clf = _get_cached(review_id, pmid, "study_class")
        if (run_all or False) and not clf:
            clf = classify_study(
                abstract=abstract, title=title,
                pub_types=_get_pub_types(article),
            )
            _set_cached(review_id, pmid, "study_class", clf)
            ran_any = True
        elif not clf:
            clf = None

        # Determine expander icon
        rob_result = _get_cached(review_id, pmid, "rob2")
        nos_result = _get_cached(review_id, pmid, "nos")
        if rob_result:
            icon = RISK_EMOJI.get(rob_result.overall, "⬜")
        elif nos_result:
            icon = nos_result.quality_emoji
        elif clf:
            icon = clf.emoji
        else:
            icon = "⬜"

        with st.expander(f"{icon} **{title[:80]}**", expanded=False):
            meta_line = f"PMID: `{pmid}` · {article.get('journal','')} {article.get('year','')}"
            st.caption(meta_line)
            if links_md:
                st.markdown(links_md, unsafe_allow_html=True)

            # Run button (per-article)
            run_one = st.button("Assess this article", key=f"rob_{pmid}")

            if (run_all or run_one) and not clf:
                clf = classify_study(
                    abstract=abstract, title=title,
                    pub_types=_get_pub_types(article),
                )
                _set_cached(review_id, pmid, "study_class", clf)
                ran_any = True

            if clf:
                # Show study design classification
                c_des, c_conf = st.columns([3, 1])
                c_des.markdown(
                    f"**Study design:** {clf.emoji} {clf.display_design}"
                )
                conf_colour = {"high": "🟢", "moderate": "🟡", "low": "🔴"}.get(
                    clf.confidence, "⬜"
                )
                c_conf.markdown(
                    f"**Confidence:** {conf_colour} {clf.confidence.capitalize()}"
                )
                if clf.signals:
                    st.caption("Signals: " + " · ".join(clf.signals[:3]))

                # ── RoB 2 (for RCTs and quasi-experimental) ───────────────────
                if clf.rob_tool == "rob2":
                    rob2 = _get_cached(review_id, pmid, "rob2")
                    if (run_all or run_one) and not rob2:
                        with st.spinner("Running RoB 2…"):
                            ft = _get_full_text(article)
                            rob2 = assess_rob2(abstract, ft)
                            _set_cached(review_id, pmid, "rob2", rob2)
                            ran_any = True

                    if rob2:
                        _render_rob2(rob2)

                # ── NOS (for observational studies) ───────────────────────────
                elif clf.rob_tool in ("nos_cohort", "nos_case_control",
                                     "nos_cross_sectional"):
                    nos = _get_cached(review_id, pmid, "nos")
                    if (run_all or run_one) and not nos:
                        with st.spinner(f"Running NOS ({clf.rob_tool})…"):
                            ft = _get_full_text(article)
                            nos = assess_nos(abstract, clf.rob_tool, ft)
                            _set_cached(review_id, pmid, "nos", nos)
                            ran_any = True

                    if nos:
                        _render_nos(nos)

                elif clf.rob_tool is None:
                    if clf.design == StudyDesign.REVIEW:
                        st.info("📚 Systematic review / meta-analysis — "
                                "quality assessed using AMSTAR-2 (not yet implemented). "
                                "Use the ⭐ Data Pooling tab for structured extraction.")
                    else:
                        st.info(f"No standardised RoB tool applies to {clf.display_design}. "
                                "Use the ⭐ Data Pooling tab for structured extraction.")
            else:
                if not run_all and not run_one:
                    st.caption("Click 'Assess this article' or '▶ Assess All' to run.")

    # ── Summary table ──────────────────────────────────────────────────────────
    rob_rows, nos_rows = [], []
    for a in articles:
        clf = _get_cached(review_id, a["pmid"], "study_class")
        rob = _get_cached(review_id, a["pmid"], "rob2")
        nos = _get_cached(review_id, a["pmid"], "nos")

        if rob:
            row = {"PMID": a["pmid"], "Title": a["title"][:50],
                   "DOI": a.get("doi") or "",
                   "Design": clf.display_design if clf else "RCT"}
            for dom in rob.domains:
                row[dom.name] = f"{dom.emoji} {dom.label}"
            row["Overall"] = f"{rob.overall_emoji} {rob.overall_label}"
            row["Rationale"] = rob.overall_rationale
            rob_rows.append(row)

        if nos:
            nos_rows.append({
                "PMID": a["pmid"], "Title": a["title"][:50],
                "DOI": a.get("doi") or "",
                "Design": clf.display_design if clf else nos.instrument,
                "Selection": f"{nos.selection.stars}/{nos.selection.max_stars}★",
                "Comparability": f"{nos.comparability.stars}/{nos.comparability.max_stars}★",
                "Outcome/Exposure": f"{nos.outcome.stars}/{nos.outcome.max_stars}★",
                "Total": f"{nos.total_stars}/{nos.max_stars}★",
                "Grade": f"{nos.quality_emoji} {nos.quality_label}",
            })

    if rob_rows:
        st.divider()
        st.markdown(f"#### RoB 2 Summary ({len(rob_rows)} RCTs)")
        df_rob = pd.DataFrame(rob_rows)
        st.dataframe(df_rob, use_container_width=True, hide_index=True)
        st.download_button("📥 Export RoB 2 (CSV)",
                           data=df_rob.to_csv(index=False),
                           file_name=f"rob2_{review_id}.csv", mime="text/csv")

    if nos_rows:
        st.divider()
        st.markdown(f"#### NOS Summary ({len(nos_rows)} observational studies)")
        df_nos = pd.DataFrame(nos_rows)
        st.dataframe(df_nos, use_container_width=True, hide_index=True)
        st.download_button("📥 Export NOS (CSV)",
                           data=df_nos.to_csv(index=False),
                           file_name=f"nos_{review_id}.csv", mime="text/csv")
    # ── Traffic Light Plot (Cochrane-style) ───────────────────────────────────
    if rob_rows or nos_rows:
        st.divider()
        st.markdown("#### 🚦 Risk of Bias Traffic Light Plot")
        st.caption("Cochrane-style visual summary. Download as PNG for publication.")
        _render_traffic_light(review_id, articles)


def _render_traffic_light(review_id, articles):
    """
    Cochrane-style traffic light plot using Plotly.
    Rows = bias domains, Columns = studies (abbreviated titles).
    Circles coloured: green=low, yellow=some concerns, red=high, grey=N/A.
    """
    import plotly.graph_objects as go

    # Collect data matrix
    ROB2_DOMAINS = [
        "Randomisation", "Deviations", "Missing data",
        "Outcome measure", "Reporting"
    ]
    NOS_DOMAINS = ["Selection", "Comparability", "Outcome/Exposure"]
    ALL_DOMAINS = ["Overall"] + ROB2_DOMAINS + NOS_DOMAINS

    COLOR_MAP = {
        "low":            "#2E7D32",
        "some_concerns":  "#F9A825",
        "high":           "#C62828",
        "good":           "#2E7D32",
        "fair":           "#F9A825",
        "poor":           "#C62828",
        "na":             "#9E9E9E",
        "no_information": "#9E9E9E",
        None:             "#E0E0E0",
    }
    SYMBOL_MAP = {
        "low": "+", "some_concerns": "?", "high": "−",
        "good": "+", "fair": "?", "poor": "−",
        "na": "?", "no_information": "?", None: "",
    }

    studies   = []
    matrix    = []   # list of {domain: (color, symbol)}

    for a in articles:
        rob2 = _get_cached(review_id, a["pmid"], "rob2")
        nos  = _get_cached(review_id, a["pmid"], "nos")
        if not rob2 and not nos:
            continue

        # Abbreviate title to 15 chars + year
        yr    = str(a.get("year",""))[-2:]
        auths = (a.get("authors") or ["?"])
        first_author = (auths[0].split()[-1] if auths and auths[0] else "?")[:12]
        label = f"{first_author} '{yr}"
        studies.append(label)

        row = {}
        if rob2:
            row["Overall"] = (rob2.overall, None)
            for dom in rob2.domains:
                key = dom.name.split(":")[0].strip()
                short = next((d for d in ROB2_DOMAINS if d.lower() in key.lower()), key[:15])
                row[short] = (dom.judgement, None)
        elif nos:
            overall_key = {"good":"low","fair":"some_concerns","poor":"high"}.get(
                nos.quality_grade, "na")
            row["Overall"] = (overall_key, None)
            for dom_name, dom_obj in [
                ("Selection",          nos.selection),
                ("Comparability",      nos.comparability),
                ("Outcome/Exposure",   nos.outcome),
            ]:
                stars = dom_obj.stars if hasattr(dom_obj, "stars") else 0
                mx    = dom_obj.max_stars if hasattr(dom_obj, "max_stars") else 3
                rating = "low" if stars >= mx*0.75 else "some_concerns" if stars >= mx*0.5 else "high"
                row[dom_name] = (rating, None)

        matrix.append(row)

    if not studies:
        st.info("Run Risk of Bias assessment first to generate the traffic light plot.")
        return

    # Determine domains actually present
    present_domains = []
    for d in ALL_DOMAINS:
        if any(d in row for row in matrix):
            present_domains.append(d)

    n_studies = len(studies)
    n_domains = len(present_domains)

    fig = go.Figure()

    for di, domain in enumerate(present_domains):
        for si, (study, row) in enumerate(zip(studies, matrix)):
            rating, _ = row.get(domain, (None, None))
            color  = COLOR_MAP.get(rating, "#E0E0E0")
            symbol = SYMBOL_MAP.get(rating, "")

            # Circle as scatter marker
            fig.add_trace(go.Scatter(
                x=[si], y=[n_domains - 1 - di],
                mode="markers+text",
                marker=dict(
                    symbol="circle",
                    size=28,
                    color=color,
                    line=dict(color="white", width=1.5),
                ),
                text=symbol,
                textfont=dict(color="white", size=13, family="Arial Black"),
                textposition="middle center",
                hovertemplate=f"<b>{study}</b><br>{domain}: {rating or 'Not assessed'}<extra></extra>",
                showlegend=False,
            ))

    # Legend entries
    for label, color, sym in [
        ("Low risk / Good",   "#2E7D32", "+"),
        ("Some concerns / Fair", "#F9A825", "?"),
        ("High risk / Poor",  "#C62828", "−"),
        ("Not assessed",      "#E0E0E0", ""),
    ]:
        fig.add_trace(go.Scatter(
            x=[None], y=[None],
            mode="markers",
            marker=dict(size=12, color=color,
                        line=dict(color="white", width=1)),
            name=label, showlegend=True,
        ))

    fig.update_layout(
        height=max(320, 60 * n_domains + 80),
        margin=dict(l=160, r=20, t=60, b=120),
        plot_bgcolor="white",
        paper_bgcolor="white",
        legend=dict(orientation="h", yanchor="top", y=-0.25,
                    xanchor="center", x=0.5),
        xaxis=dict(
            tickmode="array",
            tickvals=list(range(n_studies)),
            ticktext=studies,
            tickangle=45,
            showgrid=False, zeroline=False,
            side="top",
        ),
        yaxis=dict(
            tickmode="array",
            tickvals=list(range(n_domains)),
            ticktext=list(reversed(present_domains)),
            showgrid=False, zeroline=False,
            autorange=False,
            range=[-0.5, n_domains - 0.5],
        ),
        title=dict(
            text="Risk of Bias — Traffic Light Plot",
            x=0.5, y=1.0,
            xanchor="center", yanchor="top",
            font=dict(size=14, family="Arial"),
            pad=dict(b=20),
        ),
    )

    st.plotly_chart(fig)




def _render_rob2(rob2) -> None:
    """Display RoB 2 result in article expander."""
    st.markdown(
        f"**Overall RoB 2:** {rob2.overall_emoji} **{rob2.overall_label}**"
    )
    st.caption(rob2.overall_rationale)

    cols = st.columns(5)
    for col, dom in zip(cols, rob2.domains):
        col.markdown(
            f"<div style='text-align:center'>"
            f"<small>{dom.name.split(':')[0]}</small><br>"
            f"<span style='font-size:1.4em'>{dom.emoji}</span><br>"
            f"<small>{dom.label}</small></div>",
            unsafe_allow_html=True,
        )
    with st.expander("🔍 Signalling questions detail", expanded=False):
        for dom in rob2.domains:
            st.markdown(f"**{dom.name}** — {dom.emoji} {dom.label}")
            for sig in dom.signals:
                st.caption(f"  · {sig}")
            if dom.rationale:
                st.caption(f"  → {dom.rationale}")


def _render_nos(nos) -> None:
    """Display NOS result in article expander."""
    instrument_label = {
        "nos_cohort":           "NOS Cohort",
        "nos_case_control":     "NOS Case-Control",
        "nos_cross_sectional":  "NOS-xs2 Cross-Sectional",
    }.get(nos.instrument, nos.instrument)

    st.markdown(
        f"**{instrument_label}:** {nos.quality_emoji} **{nos.quality_label}** "
        f"— {nos.total_stars}/{nos.max_stars} stars  {nos.star_display}"
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Selection",
              f"{nos.selection.stars}/{nos.selection.max_stars}★")
    c2.metric("Comparability",
              f"{nos.comparability.stars}/{nos.comparability.max_stars}★")
    c3.metric("Outcome/Exposure",
              f"{nos.outcome.stars}/{nos.outcome.max_stars}★")

    with st.expander("🔍 Item detail", expanded=False):
        for domain in [nos.selection, nos.comparability, nos.outcome]:
            st.markdown(f"**{domain.name}**")
            for item in domain.items:
                st.caption(f"  {item}")


# ══════════════════════════════════════════════════════════════════════════════
# 📋  GRADE / SoF TAB (NEW)
# ══════════════════════════════════════════════════════════════════════════════

def _tab_grade(review_id, articles):
    from pipeline.data_pooler import extract_outcome_data

    st.markdown('''<div class="sr-section-header">
      <div class="sr-section-icon" style="background:#F0FDF4;">📋</div>
      <div><h3 style="color:var(--ink,#0F172A);">GRADE Certainty of Evidence</h3>
      </div></div>''', unsafe_allow_html=True)
    st.caption(
        "BMJ Core GRADE 2025 · Multiple outcomes · Separate assessment per study design group."
    )
    _render_ai_disclaimer()

    with st.expander("ℹ️ GRADE methodology (BMJ Core GRADE 2025)", expanded=False):
        st.markdown("""
| Symbol | Level | Meaning |
|--------|-------|---------|
| ⊕⊕⊕⊕ | **High** | Further research unlikely to change confidence |
| ⊕⊕⊕◯ | **Moderate** | Further research likely to have important impact |
| ⊕⊕◯◯ | **Low** | Further research very likely to change the estimate |
| ⊕◯◯◯ | **Very Low** | Very little confidence in the estimate |

**Starting certainty:** RCTs → High · Observational → Low

**BMJ 2025 updates:** OIS-based imprecision · Prediction interval for inconsistency ·
4-domain indirectness · Residual confounding upgrade · Observational cap at Moderate
""")

    # ── Split articles by study design ────────────────────────────────────────
    rct_articles, obs_articles, unclassified = [], [], []
    for a in articles:
        clf = _get_cached(review_id, a["pmid"], "study_class")
        if clf is None:
            unclassified.append(a)
        elif hasattr(clf, "design"):
            design_val = str(
                clf.design.value if hasattr(clf.design, "value") else clf.design
            ).lower()
            if design_val == "rct":
                rct_articles.append(a)
            else:
                obs_articles.append(a)
        else:
            unclassified.append(a)

    st.info(
        f"📊 **Study design breakdown:** "
        f"RCTs: **{len(rct_articles)}** · "
        f"Observational: **{len(obs_articles)}** · "
        f"Unclassified: **{len(unclassified)}**"
    )

    if unclassified:
        dest = st.radio(
            "Assign unclassified studies to:",
            ["RCTs", "Observational studies", "Exclude from GRADE"],
            horizontal=True, key=f"grade_unclassified_{review_id}",
        )
        if dest == "RCTs":              rct_articles += unclassified
        elif dest == "Observational studies": obs_articles += unclassified

    # ── Outcome manager ────────────────────────────────────────────────────────
    st.divider()
    st.markdown("#### 📝 Step 1 — Pre-specify Outcomes")
    st.caption(
        "Add all outcomes before running GRADE. "
        "Consistent with PROSPERO registration and Cochrane guidelines."
    )

    _out_key = f"grade_outcomes_{review_id}"
    if _out_key not in st.session_state:
        st.session_state[_out_key] = [
            {"name": "Primary outcome", "type": "binary",
             "followup": "", "importance": "Critical"}
        ]

    outcomes = st.session_state[_out_key]

    # Render outcome rows
    to_delete = None
    for oi, out in enumerate(outcomes):
        oc1, oc2, oc3, oc4, oc5 = st.columns([3, 2, 2, 2, 1])
        outcomes[oi]["name"] = oc1.text_input(
            "Outcome name", value=out["name"],
            key=f"oname_{review_id}_{oi}",
            label_visibility="collapsed",
            placeholder="e.g. Overall survival")
        outcomes[oi]["type"] = oc2.selectbox(
            "Type", ["binary", "continuous", "time-to-event"],
            index=["binary","continuous","time-to-event"].index(out.get("type","binary")),
            key=f"otype_{review_id}_{oi}",
            label_visibility="collapsed")
        outcomes[oi]["followup"] = oc3.text_input(
            "Follow-up", value=out.get("followup",""),
            key=f"ofu_{review_id}_{oi}",
            label_visibility="collapsed",
            placeholder="e.g. 30 days")
        outcomes[oi]["importance"] = oc4.selectbox(
            "Importance", ["Critical", "Important", "Not important"],
            index=["Critical","Important","Not important"].index(
                out.get("importance","Critical")),
            key=f"oimp_{review_id}_{oi}",
            label_visibility="collapsed")
        if oc5.button("🗑️", key=f"odel_{review_id}_{oi}") and len(outcomes) > 1:
            to_delete = oi

    if to_delete is not None:
        outcomes.pop(to_delete)
        st.rerun()

    if st.button("➕ Add outcome", key=f"oadd_{review_id}"):
        outcomes.append({"name":"", "type":"binary",
                         "followup":"", "importance":"Important"})
        st.rerun()

    st.session_state[_out_key] = outcomes

    # ── Per-outcome data extraction ────────────────────────────────────────────
    st.divider()
    st.markdown("#### 📊 Step 2 — Extract & Verify Outcome Data")
    st.caption(
        "LLM extracts per-outcome data from each article. "
        "Review and correct values before running GRADE."
    )

    _ext_key = f"grade_extracted_{review_id}"
    if _ext_key not in st.session_state:
        st.session_state[_ext_key] = {}
    extracted = st.session_state[_ext_key]

    col_ext, col_clr = st.columns([2, 1])
    with col_ext:
        if st.button("▶ Extract data for all outcomes",
                     key=f"grade_extract_{review_id}", type="primary"):
            _prog = st.progress(0, text="Extracting outcome data…")
            _total = len(outcomes) * len(articles)
            _done  = 0
            for out in outcomes:
                oname = out["name"]
                otype = out["type"]
                if oname not in extracted:
                    extracted[oname] = {}
                for a in articles:
                    pmid = a["pmid"]
                    if pmid not in extracted[oname]:
                        abstract = a.get("abstract","")
                        ft       = article_repo.get_full_text(pmid) or ""
                        text     = ft[:3000] if ft else abstract
                        result   = extract_outcome_data(
                            text, oname, otype, pmid=pmid)
                        extracted[oname][pmid] = result
                    _done += 1
                    _prog.progress(_done/_total,
                                   text=f"Extracting: {oname} — {_done}/{_total}")
            _prog.empty()
            st.session_state[_ext_key] = extracted
            st.rerun()
    with col_clr:
        if st.button("🔄 Clear extracted data",
                     key=f"grade_ext_clr_{review_id}"):
            st.session_state.pop(_ext_key, None)
            st.rerun()

    # Show extracted data per outcome for verification
    for out in outcomes:
        oname = out["name"]
        odata = extracted.get(oname, {})
        if not odata:
            continue
        with st.expander(
            f"📋 {oname} ({out['type']}, {out.get('followup','')}) "
            f"— {sum(1 for v in odata.values() if v.get('found'))} studies reporting",
            expanded=False
        ):
            st.caption("Review and correct extracted values. "
                       "Changes saved automatically.")
            _edit_key = f"grade_edits_{review_id}_{oname}"
            if _edit_key not in st.session_state:
                st.session_state[_edit_key] = {}
            edits = st.session_state[_edit_key]

            for a in articles:
                pmid  = a["pmid"]
                title = (a.get("title") or "")[:60]
                row   = odata.get(pmid, {})
                if not row:
                    continue
                found = row.get("found", False)
                ec1, ec2, ec3, ec4 = st.columns([3, 2, 2, 2])
                ec1.markdown(
                    f"**{title}**  "
                    f"{'✅' if found else '❌ Not reported'}"
                )
                edits[f"{pmid}_n"]  = ec2.text_input(
                    "N", value=edits.get(f"{pmid}_n",
                        str(row.get("n_participants","NR"))),
                    key=f"ge_n_{review_id}_{oname}_{pmid}",
                    label_visibility="collapsed")
                edits[f"{pmid}_eff"] = ec3.text_input(
                    "Effect (95% CI)",
                    value=edits.get(f"{pmid}_eff",
                        str(row.get("effect_estimate","NR"))),
                    key=f"ge_eff_{review_id}_{oname}_{pmid}",
                    label_visibility="collapsed")
                edits[f"{pmid}_fu"] = ec4.text_input(
                    "Follow-up",
                    value=edits.get(f"{pmid}_fu",
                        str(row.get("follow_up", out.get("followup","NR")))),
                    key=f"ge_fu_{review_id}_{oname}_{pmid}",
                    label_visibility="collapsed")
            st.session_state[_edit_key] = edits

    # ── GRADE assessment ───────────────────────────────────────────────────────
    st.divider()
    st.markdown("#### 🏆 Step 3 — Run GRADE Assessment")

    grade_key = f"grade_{review_id}"

    col_run, col_clr2 = st.columns([2, 1])
    with col_run:
        run_btn = st.button(
            "▶ Run GRADE for all outcomes (both groups)",
            type="primary", key="grade_run")
    with col_clr2:
        if st.button("🔄 Clear GRADE results", key="grade_clear"):
            st.session_state.pop(grade_key, None)
            try:
                ai_repo.save_analysis(
                    f"review_{review_id}", "grade", {})
            except Exception:
                pass
            st.rerun()

    if run_btn:
        all_results = {}  # {outcome_name: {design_key: GRADEAssessment}}

        for out in outcomes:
            oname  = out["name"]
            otype  = out["type"]
            odata  = extracted.get(oname, {})
            edits  = st.session_state.get(
                f"grade_edits_{review_id}_{oname}", {})

            # Build pooled data for this outcome using verified extractions
            def _pool_for_outcome(group_arts):
                rows = []
                for a in group_arts:
                    pmid = a["pmid"]
                    row  = odata.get(pmid, {})
                    n    = edits.get(f"{pmid}_n",
                               row.get("n_participants","NR"))
                    eff  = edits.get(f"{pmid}_eff",
                               row.get("effect_estimate","NR"))
                    rows.append({
                        "Title":          (a.get("title",""))[:50],
                        "Sample size":    n,
                        "Primary Result": eff,
                        "Study Design":   (a.get("source","") or ""),
                    })
                return rows

            def _run_group(group_arts, design_key, design_label):
                if not group_arts:
                    return
                rob2_list = [r for a in group_arts
                             if (r := _get_cached(review_id, a["pmid"], "rob2"))
                             is not None]
                nos_list  = [n for a in group_arts
                             if (n := _get_cached(review_id, a["pmid"], "nos"))
                             is not None]
                pool_list = _pool_for_outcome(group_arts)

                with st.spinner(
                    f"GRADE: {oname} — {design_label}…"
                ):
                    try:
                        grade = assess_grade(
                            rob2_assessments=rob2_list,
                            nos_assessments=nos_list,
                            pooled_data=pool_list,
                            outcome=oname,
                            study_design=design_key,
                        )
                        all_results.setdefault(oname, {})[design_key] = grade
                    except Exception as e:
                        logger.error("GRADE %s/%s: %s",
                                     oname, design_label, e)
                        st.error(f"GRADE error ({oname}/{design_label}): {e}")

            if rct_articles:
                _run_group(rct_articles,  "rct",           "RCTs")
            if obs_articles:
                _run_group(obs_articles,  "observational", "Observational")

        if all_results:
            st.session_state[grade_key] = all_results
            try:
                import dataclasses
                serialisable = {
                    oname: {dk: dataclasses.asdict(g)
                            for dk, g in dmap.items()}
                    for oname, dmap in all_results.items()
                }
                ai_repo.save_analysis(
                    f"review_{review_id}", "grade", serialisable)
            except Exception as e:
                logger.warning("Could not persist GRADE: %s", e)

    # ── Restore from DB if needed ──────────────────────────────────────────────
    grade_results = st.session_state.get(grade_key)
    if not grade_results:
        raw_grade = ai_repo.get_analysis(f"review_{review_id}", "grade")
        if raw_grade and isinstance(raw_grade, dict):
            try:
                restored = {}
                for oname, dmap in raw_grade.items():
                    if not isinstance(dmap, dict):
                        continue
                    restored[oname] = {}
                    for design_key, gd in dmap.items():
                        if not isinstance(gd, dict):
                            continue
                        kwargs = {}
                        for k, v in gd.items():
                            if isinstance(v, dict) and "direction" in v:
                                kwargs[k] = GRADEFactor(**v)
                            else:
                                kwargs[k] = v
                        restored[oname][design_key] = GRADEAssessment(**kwargs)
                grade_results = restored
                st.session_state[grade_key] = grade_results
            except Exception as e:
                logger.warning("Could not restore GRADE: %s", e)

    if not grade_results:
        return

    # ── Combined SoF table — Cochrane format with outcome header rows ──────────
    st.divider()
    st.markdown("#### 📋 Summary of Findings — BMJ Core GRADE 2025")
    st.caption(
        "One section per outcome · "
        "One row per study design group · "
        "Certainty assessed separately (RCTs start High, Observational start Low)"
    )

    # Streamlit preview table
    preview_rows = []
    for out in outcomes:
        oname   = out["name"]
        ofu     = out.get("followup","")
        dmap    = grade_results.get(oname, {})
        if not dmap:
            continue
        # Section header row
        preview_rows.append({
            "Outcome":        f"📌 {oname}" + (f" ({ofu})" if ofu else ""),
            "Study design":   "—", "No. studies (N)": "—",
            "Effect estimate":"—", "Risk of bias":"—",
            "Inconsistency":  "—", "Indirectness":"—",
            "Imprecision":    "—", "Publication bias":"—",
            "Certainty":      "—",
        })
        for design_key in ["rct","observational"]:
            g = dmap.get(design_key)
            if g:
                row = g.to_sof_row()
                row["Outcome"] = ""  # blank — outcome shown in header
                preview_rows.append(row)

    if preview_rows:
        st.dataframe(pd.DataFrame(preview_rows),
                     use_container_width=True, hide_index=True)

    # ── Manual event counts ────────────────────────────────────────────────────
    _manual_ev = {}
    with st.expander("✏️ Manual event count entry (if not auto-extracted)",
                     expanded=False):
        st.caption("Format: events/total e.g. '19/266'")
        for out in outcomes:
            oname = out["name"]
            dmap  = grade_results.get(oname, {})
            if not dmap: continue
            st.markdown(f"**{oname}**")
            for g_key, g_label in [("rct","RCTs"),
                                    ("observational","Observational")]:
                if g_key not in dmap: continue
                mc1, mc2 = st.columns(2)
                _manual_ev[f"{oname}_{g_key}_int"] = mc1.text_input(
                    f"{g_label} — Intervention arm",
                    key=f"me_int_{g_key}_{oname}_{review_id}",
                    placeholder="e.g. 19/266")
                _manual_ev[f"{oname}_{g_key}_comp"] = mc2.text_input(
                    f"{g_label} — Comparator arm",
                    key=f"me_comp_{g_key}_{oname}_{review_id}",
                    placeholder="e.g. 44/359")

    # ── HTML SoF table (Cochrane publication quality) ─────────────────────────
    sof_html = _build_sof_html_multi(grade_results, outcomes, _manual_ev)
    st.markdown(sof_html, unsafe_allow_html=True)

    sof_html_full = f"""<!DOCTYPE html><html><head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; font-size: 11pt; margin: 20px; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th {{ background:#1B4F8A; color:white; padding:6px 8px;
        text-align:center; font-size:10pt; border:1px solid #999; }}
  td {{ padding:5px 8px; border:1px solid #ccc;
        text-align:center; font-size:10pt; vertical-align:middle; }}
  .outcome-header {{ background:#2C3E50; color:white; font-weight:bold;
                     text-align:left; font-size:11pt; }}
  .certainty-high {{ color:#1B5E20; font-weight:bold; }}
  .certainty-moderate {{ color:#F57F17; font-weight:bold; }}
  .certainty-low {{ color:#E65100; font-weight:bold; }}
  .certainty-very_low {{ color:#B71C1C; font-weight:bold; }}
</style></head><body>{sof_html}</body></html>"""

    c_dl1, c_dl2, c_dl3 = st.columns(3)
    with c_dl1:
        st.download_button(
            "📥 Download SoF (HTML — opens in Word)",
            data=sof_html_full,
            file_name=f"sof_table_{review_id}.html",
            mime="text/html", use_container_width=True)
    with c_dl2:
        all_rows = []
        for out in outcomes:
            dmap = grade_results.get(out["name"], {})
            for g in dmap.values():
                r = g.to_sof_row()
                r["Outcome"] = out["name"]
                all_rows.append(r)
        if all_rows:
            st.download_button(
                "📥 Export SoF (CSV)",
                data=pd.DataFrame(all_rows).to_csv(index=False),
                file_name=f"grade_sof_{review_id}.csv",
                mime="text/csv", use_container_width=True)
    with c_dl3:
        combined_export = {
            oname: {dk: g.to_export_dict() for dk, g in dmap.items()}
            for oname, dmap in grade_results.items()
        }
        st.download_button(
            "📥 Export Full GRADE (JSON)",
            data=json.dumps(combined_export, indent=2),
            file_name=f"grade_{review_id}.json",
            mime="application/json", use_container_width=True)

    # ── Per-outcome detailed breakdown ─────────────────────────────────────────
    st.divider()
    st.markdown("#### Detailed Factor Breakdown")

    for out in outcomes:
        oname = out["name"]
        dmap  = grade_results.get(oname, {})
        if not dmap:
            continue
        st.markdown(f"##### 📌 {oname}")
        for design_key, design_label in [
            ("rct","RCTs"), ("observational","Observational")
        ]:
            grade = dmap.get(design_key)
            if not grade:
                continue
            emoji   = CERTAINTY_EMOJI.get(grade.final_certainty, "⬜")
            display = CERTAINTY_DISPLAY.get(grade.final_certainty,
                                            grade.final_certainty)
            with st.expander(
                f"{emoji} **{design_label}** — {display} "
                f"({grade.n_studies} studies, n={grade.n_participants or 'NR'})",
                expanded=False,
            ):
                st.info(grade.certainty_meaning)
                st.caption(f"Rationale: {grade.certainty_rationale}")

                mc1, mc2, mc3, mc4 = st.columns(4)
                mc1.metric("Studies",      grade.n_studies)
                mc2.metric("Participants", grade.n_participants or "NR")
                mc3.metric("Starting",     grade.starting_certainty.upper())
                mc4.metric("Final",
                           grade.final_certainty.replace("_"," ").upper())

                st.markdown("**Downgrade / Upgrade Factors**")
                factor_cols = st.columns(5)
                for col, factor in zip(factor_cols, [
                    grade.risk_of_bias, grade.inconsistency,
                    grade.indirectness, grade.imprecision,
                    grade.publication_bias,
                ]):
                    icon  = ("🔴" if factor.levels==2 else "🟡") \
                            if factor.direction=="downgrade" else \
                            ("🟢" if factor.direction=="upgrade" else "🟢")
                    label = (f"↓{factor.levels}" if factor.direction=="downgrade"
                             else f"↑{factor.levels}" if factor.direction=="upgrade"
                             else "—")
                    col.markdown(
                        f"<div style='text-align:center'>"
                        f"<small>{factor.name}</small><br>"
                        f"<span style='font-size:1.3em'>{icon}</span><br>"
                        f"<small>{label}</small></div>",
                        unsafe_allow_html=True)

                with st.expander("🔍 Factor rationales", expanded=False):
                    for f in grade.all_factors:
                        if f.direction != "none" and f.rationale:
                            st.markdown(
                                f"**{f.name}** — "
                                f"{'↓'*f.levels} Downgrade"
                                if f.direction=="downgrade"
                                else f"**{f.name}** — ↑ Upgrade")
                            st.caption(f"  {f.rationale}")

                # Reporting template
                n_word = (
                    f"{grade.n_studies} "
                    f"{'randomised trial' if design_key=='rct' else 'observational stud'}"
                    f"{'y' if grade.n_studies==1 else 'ies'}"
                )
                st.divider()
                st.markdown("**📝 Reporting Template**")
                st.code(
                    f"The certainty of evidence for {grade.outcome} based on "
                    f"{n_word} (n={grade.n_participants or 'NR'}) was assessed "
                    f"using the GRADE approach (BMJ Core GRADE 2025). "
                    f"The certainty was rated as "
                    f"{grade.final_certainty.replace('_',' ')} "
                    f"({CERTAINTY_DISPLAY.get(grade.final_certainty,'')}). "
                    f"{grade.certainty_rationale}",
                    language=None)



def _build_sof_html_multi(grade_results: dict,
                           outcomes: list,
                           manual_events: dict = None) -> str:
    """
    Cochrane-format multi-outcome SoF table.
    Each outcome gets a dark header row followed by one data row per design group.
    Matches the reference table format exactly.
    """
    if manual_events is None:
        manual_events = {}

    CERT_SYMBOLS = {
        "high": "⊕⊕⊕⊕", "moderate": "⊕⊕⊕◯",
        "low":  "⊕⊕◯◯",  "very_low": "⊕◯◯◯",
    }
    CERT_COLORS = {
        "high":     "#1B5E20", "moderate": "#F57F17",
        "low":      "#E65100", "very_low": "#B71C1C",
    }

    def _fmt(factor) -> str:
        if factor.direction == "downgrade":
            return "⬇ Serious" if factor.levels==1 else "⬇⬇ Very serious"
        if factor.direction == "upgrade": return "⬆ Upgrade"
        return "Not serious"

    html = """
<table>
<thead>
<tr>
  <th rowspan="2" style="text-align:left;min-width:160px;">
    Outcome<br><small>(follow-up)</small></th>
  <th rowspan="2">Study design<br>(No. studies, N)</th>
  <th colspan="5" style="background:#2C5F8A;">Certainty assessment</th>
  <th colspan="2" style="background:#2C5F8A;">Study event rates</th>
  <th rowspan="2">Relative effect<br>(95% CI)</th>
  <th rowspan="2">Overall<br>certainty</th>
</tr>
<tr>
  <th>Risk of bias</th>
  <th>Inconsistency</th>
  <th>Indirectness</th>
  <th>Imprecision</th>
  <th>Publication bias</th>
  <th>With intervention</th>
  <th>With comparator</th>
</tr>
</thead>
<tbody>
"""

    footnotes = []

    for out in outcomes:
        oname = out["name"]
        ofu   = out.get("followup", "")
        dmap  = grade_results.get(oname, {})
        if not dmap:
            continue

        n_rows = sum(1 for dk in ["rct","observational"] if dk in dmap)

        # Outcome header row (dark background, spans all columns)
        out_label = oname + (f" (follow-up: {ofu})" if ofu else "")
        html += f"""
<tr>
  <td colspan="11" class="outcome-header"
      style="background:#2C3E50;color:white;font-weight:bold;
             text-align:left;padding:7px 10px;">
    {out_label}
  </td>
</tr>
"""

        for design_key, design_label in [("rct","RCTs"),
                                          ("observational","Observational")]:
            g = dmap.get(design_key)
            if not g:
                continue

            sym   = CERT_SYMBOLS.get(g.final_certainty, "")
            color = CERT_COLORS.get(g.final_certainty, "#000")
            cert_cell = (
                f'<span style="color:{color};font-size:1.1em;">{sym}</span><br>'
                f'<span style="color:{color};font-weight:bold;">'
                f'{g.final_certainty.replace("_"," ").upper()}</span>'
            )

            ev_int  = manual_events.get(f"{oname}_{design_key}_int",  "") or "NR"
            ev_comp = manual_events.get(f"{oname}_{design_key}_comp", "") or "NR"

            design_cell = (
                f"<b>{'RCTs' if design_key=='rct' else 'Observational'}</b><br>"
                f"{g.n_studies} study" if g.n_studies==1
                else
                f"<b>{'RCTs' if design_key=='rct' else 'Observational'}</b><br>"
                f"{g.n_studies} studies, n={g.n_participants or 'NR'}"
            )

            html += f"""
<tr>
  <td style="text-align:left;color:#555;font-size:0.9em;">
    {'Critical' if out.get('importance')=='Critical' else out.get('importance','')}</td>
  <td style="text-align:left;">{design_cell}</td>
  <td>{_fmt(g.risk_of_bias)}</td>
  <td>{_fmt(g.inconsistency)}</td>
  <td>{_fmt(g.indirectness)}</td>
  <td>{_fmt(g.imprecision)}</td>
  <td>{_fmt(g.publication_bias)}</td>
  <td>{ev_int}</td>
  <td>{ev_comp}</td>
  <td style="text-align:center;">{g.relative_effect}</td>
  <td style="text-align:center;">{cert_cell}</td>
</tr>
"""
            # Collect footnotes
            for f in g.all_factors:
                if f.direction != "none" and f.rationale:
                    footnotes.append(
                        f"<b>{oname} — {'RCTs' if design_key=='rct' else 'Obs'} "
                        f"— {f.name}:</b> {f.rationale}")

    html += "</tbody></table>"

    if footnotes:
        html += ("<br><small><b>Explanations:</b><br>"
                 + "<br>".join(f"• {fn}" for fn in footnotes)
                 + "</small>")

    return html



# ── Helper utilities ───────────────────────────────────────────────────────────

def _get_pub_types(article: dict) -> Optional[List[str]]:
    """Extract PubMed publication types from article venue field."""
    venue = article.get("venue") or ""
    if not venue:
        return None
    return [pt.strip() for pt in venue.split(";") if pt.strip()]


def _get_full_text(article: dict) -> str:
    """Get full text if available (stored in session_state by full-text pipeline)."""
    return ""   # Full text integration deferred — abstract is primary input